/////////////////////////////////////////////////////////////////////////////
// qcengine_mini.js
// Copyright 2000-2016 Eric Johnston
// qcengine@machinelevel.com
//
//  License:
//    (This is similar to the zlib license, with item 4 added and modifications
//     which apply only to commercial use.) 
//
//  This software is provided 'as-is', without any express or implied
//  warranty. In no event will the authors be held liable for any damages
//  arising from the use of this software.
//
//  Commercial use requires written authorization from the author.
//  Please contact me, as I can also help make sure you're getting the best use
//  from this software, and have the most up-to-date version.
//
//  Permission is granted to anyone to use this software for non-commercial
//  purposes, and to alter it and redistribute it freely, subject to the
//  following restrictions:
//
//  1. The origin of this software must not be misrepresented; you must not
//     claim that you wrote the original software. If you use this software
//     in a product, an acknowledgment in the product documentation would be
//     appreciated but is not required.
//  2. Altered source versions must be plainly marked as such, and must not be
//     misrepresented as being the original software.
//  3. This notice may not be removed or altered from any source distribution.
//  4. If you find this material useful, I'd love to know. If there is an email
//     address listed above this notice, please consider sending me a note.
//  (end of license text)
//
//  Commercial interest: There are several versions of this software, each
//  designed to maximize speed under different hardware and/or language constraints.
//  For more info, please contact me at qcengine@machinelevel.com
//


///////////////////////////////////////////////////////////////
// Major tasks in process: (all are started, none are finished)
//      1. Deferred block jobs
// DONE 2. Script window
// DONE 3. Animation for circles window
//      4. GPU block job
// DONE 5. Finish circles window
//      6. Allow all ops in staff window
// DONE 7. Dim staff lines where not in use
//      8. Enable animation for staff scripts
//      9. Print timing of staff scripts


/////////////////////////////////////////////////////////////////////////////
// The QReg class simulates qubit registers for a quantum computer.
//   numQubits       is the number of qubits to simulate (any positive integer)
//   doublePrecision is a bool which determines whether we use single or double floats
//
// Some key methods:
//   activate()      will allocate the qubit data and ready it for computation.
//
//   deactivate()    will free the qubit data memory when you're done. You can
//                   call activate() again if you like, but the previous data is lost.
//
//   bytesRequired() determines how much memory the qubit data will take. This may be
//                   called on an active or inactive QReg.
//
// BIG FAT WARNING: After creating a QReg, be sure to call bytesRequired() to see
//                  how much memory is going to be required to activate the
//                  register. You might be surprised. Here are some examples:
//
//                     1-qubit single precision: (2^1) *4*2 = 16 bytes
//                    10-qubit single precision: (2^10)*4*2 = 8 KB
//                    20-qubit single precision: (2^20)*4*2 = 8 MB
//                    32-qubit single precision: (2^32)*4*2 = 32 GB
//                    64-qubit single precision: (2^64)*4*2 = 128 exabytes
//                                   (one exabyte = about a million million MB)
//
//                  At 164 qubits, the number of bytes required exceeds the number of
//                  atoms in the Earth. Please let me know if you get this working.
//
//                  Note that even if your machine can handle the data size, some computations
//                  may take longer than the estimated remaining life of the universe.
//
var y,ca=[];function da(a,c){if(ca[c]&&0<ca[c].length){var d=ca[c].pop();d.set(a);return d}return null}function A(a,c){null==c&&(c=a&&a.da?a.H:32);c=c+31&-32;var d=da(a,c);return d?d:new C(a,c)}
function C(a,c){null==c&&(c=a&&a.da?a.H:32);c=c+31&-32;var d=da(a,c);if(d)return d;this.da=!0;this.H=c;this.values=new Uint32Array(new ArrayBuffer(c/8));this.Pe=function(b){var a=b+31&-32;this.H=a;b=this.values;this.values=new Uint32Array(new ArrayBuffer(a/8));for(a=0;a<b.length;++a)this.values[a]=b[a];this.values[this.values.length-1]=0};this.set=function(b){for(var a=0;a<this.values.length;++a)this.values[a]=0;if(b)if(b.da)for(a=0;a<this.values.length&&a<b.values.length;++a)this.values[a]=b.values[a];
else this.values[0]=b};this.set(a);this.bb=function(){ca[this.H]||(ca[this.H]=[]);ca[this.H].push(this)};this.gd=function(b){if(!b.da)return(this.values[0]&b)==b;for(var a=0;a<this.values.length&&a<b.values.length;++a)if((this.values[a]&b.values[a])!=(0|b.values[a]))return!1;return!0};this.ib=function(b){if(!b.da)return 0!=(this.values[0]&b);for(var a=0;a<this.values.length&&a<b.values.length;++a)if(0!=(this.values[a]&b.values[a]))return!0;return!1};this.Id=function(b){if(!b.da)return this.values[0]==
b;for(var a=0;a<this.values.length&&a<b.values.length;++a)if(this.values[a]!=b.values[a])return!1;return!0};this.R=function(b,a){this.eb(b,1,a)};this.O=function(b){return this.Mb(b,1)};this.Hd=function(){for(var b=0;b<this.values.length;++b)this.values[b]=~this.values[b]};this.eb=function(b,a,c){c&=a;var h=0|b/32;b%=32;h<this.values.length&&(0==b?(this.values[h]&=~a,this.values[h]|=c):(this.values[h]&=~(a<<b),this.values[h]|=c<<b,h+1<this.values.length&&(this.values[h+1]&=~(a>>>32-b),this.values[h+
1]|=c>>>32-b)))};this.Mb=function(b,a){null==a&&(a=-1);var c=0|b/32,h=b%32,d=0;if(c<this.values.length){if(0==h)return this.values[c]&a;d=this.values[c]>>>h;c+1<this.values.length&&(d|=this.values[c+1]<<32-h);return d&a}};this.la=function(b){if(b)if(b.da)for(var a=0;a<this.values.length;++a)this.values[a]=a<b.values.length?this.values[a]&b.values[a]:0;else this.values[0]|=b};this.v=function(b){if(b)if(b.da)for(var a=0;a<this.values.length&&a<b.values.length;++a)this.values[a]|=b.values[a];else this.values[0]|=
b};this.od=function(b){if(b)if(b.da)for(var a=0;a<this.values.length&&a<b.values.length;++a)this.values[a]^=b.values[a];else this.values[0]^=b};this.Uc=function(){for(var b=0;b<this.values.length;++b)if(this.values[b])return!1;return!0};this.P=function(){for(var b=0;b<this.H;++b)if(this.O(b))return b;return-1};this.V=function(){for(var b=this.H-1;0<=b;--b)if(this.O(b))return b;return-1};this.Jb=function(){for(var b=0,a=0;a<this.values.length;++a)for(var c=this.values[a];c;)b+=c&1,c>>>=1;return b};
this.ac=function(){this.values[this.values.length-1]&-2147483648&&this.Pe(this.H+1);for(var b=this.values.length-1;0<b;--b)this.values[b]=this.values[b]<<1|this.values[b-1]>>>31;this.values[0]<<=1};this.Eb=function(){for(var b=0;b<this.values.length-1;++b)this.values[b]=this.values[b]>>>1|this.values[b+1]<<31;this.values[this.values.length-1]>>>=1}}function D(a){return a.da?a.Mb(0,-1):a}function ea(a){return a.da?a:new C(a)}function fa(a,c){return a.da?a.O(c):a>>c&1}
function ha(a){if(a.da)return a.P();for(var c=0;32>c;++c)if(a&1<<c)return c;return-1}function ia(a){if(a.da)return a.V();for(var c=31;0<=c;--c)if(a&1<<c)return c;return-1}function E(a){return a?a.da?a.Uc():!1:!0}function ja(a,c){return a||c?a&&c?a.Id(c):!1:!0}function ka(a){var c=[];if(a)if(a.da)for(var d=0;d<a.values.length&&2>c.length;++d){if(a.values[d])for(var b=0;32>b&&2>c.length;++b)a.values[d]&1<<b&&c.push(32*d+b)}else for(d=0;32>d&&2>c.length;++d)a&1<<d&&c.push(d);return c}
function F(a,c){var d=A(0,32+c);d.set(0);d.eb(c,a,a);return d};function G(a,c){this.a=c;this.c=a;this.ea=1<<a-1;this.aa=this.ea-1;this.values=null;c.Md||(c.Kd?(this.af=c.tc,c.tc+=2*c.Od,this.values=c.Kd.subarray(this.af,c.tc)):this.values=c.Kb?new Float64Array(new ArrayBuffer(c.td)):new Float32Array(new ArrayBuffer(c.td)));this.j=null;this.Fa=function(){if(this.j&&(this.j.ff(0),!webgl_blocks.Y))return;for(var a=1<<this.c,a=2*a,b=0;b<a;++b)this.values[b]=0;this.j&&webgl_blocks.Y&&this.j.ta("setZero",this.values)};this.$b=function(a){if(this.j&&(this.j.Tf(a),!webgl_blocks.Y))return;
for(var b=1<<this.c,b=2*b,c=0;c<b;++c)this.values[c]*=a;this.j&&webgl_blocks.Y&&this.j.ta("scaleValues",this.values)};this.Ob=function(a){if(this.j){this.j.ff(1);for(var b=0;b<this.c;++b){var c=1<<b;a&c&&this.j.Pd(c)}if(!webgl_blocks.Y)return}c=1<<this.c;c*=2;for(b=0;b<c;++b)this.values[b]=0;this.values[2*a]=1;this.j&&webgl_blocks.Y&&this.j.ta("initialize",this.values)};this.tb=function(){this.j&&(this.j.tb(),this.j=null);delete this.values;this.values=null}}
function H(a,c){this.c=a;this.ea=1<<a-1;this.aa=this.ea-1;this.i=[];a-1<=c.uc?(this.i[0]=new G(a-1,c),this.i[1]=new G(a-1,c)):(this.i[0]=new H(a-1,c),this.i[1]=new H(a-1,c));this.Fa=function(){this.i[0].Fa();this.i[1].Fa()};this.$b=function(a){this.i[0].$b(a);this.i[1].$b(a)};this.Ob=function(a){var b=a>>this.c-1;this.i[b].Ob(a&this.aa);this.i[1-b].Fa()};this.tb=function(){this.i[0].tb();this.i[1].tb();delete this.i[0];delete this.i[1];delete this.i;this.i=null};this.If=function(){var a=this.i[0];
this.i[0]=this.i[1];this.i[1]=a}}
function la(a,c){this.a=c;this.c=a;this.ea=1<<a-1;this.aa=this.ea-1;this.values=new C(0,this.c);this.Fa=function(){this.values.set(0)};this.$b=function(){};this.Ob=function(a){this.values.set(a)};this.read=function(a){var b=new C(this.values);b.la(a);return b};this.tb=function(){};this.X=function(a){this.values.od(a)};this.G=function(a,b){this.values.gd(b)&&this.X(a)};this.sa=function(){};this.pa=function(){};this.na=function(a,b,c,f,h){this.values.gd(b)&&this.pa(a,c,f,h)};this.Db=function(){};this.hb=
function(){return 1};this.Pa=function(a){return this.values.gd(a)?1:0};this.ja=function(a){return this.values.Id(a)?new I(1,0):new I(0,0)};this.Ea=function(a,b,c){.25<=b*b+c*c&&this.values.set(a)}}
function K(a,c,d){this.za=!0;this.Md=!1;this.I=this.Ld=null;this.Cb=function(b,a,c){null==a&&(a=b);null==c&&(c=!1);this.ve();this.c=b;this.$a=1<<this.c;this.J=new C(0,this.c);for(b=0;b<this.c;++b)this.J.R(b,1);this.uc=a;this.Od=1<<this.uc;this.le=(this.Kb=c)?8:4;this.td=this.Od*this.le*2;this.Dc=Array(this.c);for(b=0;b<this.c;++b)this.Dc[b]=!1};this.pb=function(){this.Kd=null;this.tc=0;this.Md=!1;this.ka=null;this.Aa=!1;new C(0,this.c);this.xa=Array(this.c);if(!this.active){28<this.c?(this.Ua=!0,
console.log("This QC has "+this.c+" qubits, which would be "+(Math.pow(2,this.c+3)/1073741824).toFixed(1)+" GB, so I'm going to disable simulation."),52<this.c&&console.log("In fact, anything more than 32 bits may not work at all. Watch out.")):this.Ua=!1;this.L=this.Ua?new la(this.c,this):this.c<=this.uc?new G(this.c,this):new H(this.c,this);this.Tc();this.L.Ob(0);this.xf();this.active=!0;for(var b in this.ya)this.ya[b].Td();this.K()}};this.Df=function(b,a){null==this.ka&&(this.ka=new ma);this.ka.reset(this,
b,a);this.ka.Lf();this.Aa=!0};this.Hf=function(){this.ka&&this.ka.ce();this.Aa=!1};this.Cf=function(b,a){null==this.I&&(this.I=new na);this.I.reset(this,b,a);this.I.Kf();this.I.active=!0};this.Gf=function(){this.I&&(this.I.be(),this.I.active=!1)};this.Qe=function(){var b=[],a;for(a in this.ya){var c=this.ya[a];b.push(new Option(c.name,c.name))}return b};this.pc=function(b){this.Rd&&(b>>=1);for(var a in this.ya){var c=this.ya[a],h=b-c.B;if(0<=h&&h<c.H)return c.name}return""};this.Sc=function(b){var a=
"";this.Rd&&(a=b&1?" - ":" +",b>>=1);for(var c in this.ya){var h=this.ya[c],d=b-h.B;if(0<=d&&d<h.H)return(1<<d).toString(16)+a}b=F(1,b);if(b.da){c="";h=!1;for(d=b.values.length-1;0<=d;--d){var l=b.values[d].toString(16),m=l.length;if(h&&d<b.values.length-1)for(;8>m++;)c+="0";if(h||b.values[d]||0==d)c+=l;b.values[d]&&(h=!0)}b=c}else b=b.toString(16);return b+a};this.Cc=function(){for(var b=0;b<this.D.length;++b)this.D[b].Cc&&this.D[b].Cc()};this.ve=function(){if(this.active){for(var b in this.ya)this.ya[b].release();
this.active=!1;this.L.tb();delete this.L;this.L=null;this.Tc();"function"==typeof CollectGarbage&&CollectGarbage()}};this.rf=function(b){for(var a=0,c=0;a+b<=this.c;){for(c=0;c<b&&!this.Dc[a+c];++c);if(c==b){for(c=0;c<b;++c)this.Dc[a+c]=!0;return a}a++}return-1};this.qf=function(b){for(var a=0;a<b;++a)this.Dc[void 0+a]=!1};this.K=function(){if(!(!this.za||L&&L.Yf))for(var b=0;b<this.D.length;++b)this.D[b].K()};this.message=function(b,a,c){for(var h=0;h<this.D.length;++h)this.D[h].message(b,a,c)};
this.ia=function(b,a){null==b&&(b=this.J);b=D(b);if(a){var c=D(a);if((c&this.va)==c)return}this.va&=~b};this.Tc=function(){this.ia(this.J)};this.Wd=function(b,a){b=D(b);a=D(a);this.va|=b;this.qa&=~b;this.qa|=a&b};this.xf=function(){this.Wd(this.J,0)};this.vd=function(b){return 0!=(this.qa&b)};this.Ic=function(b){return 0!=(this.va&b)};this.Jf=function(){this.fc=!this.fc;this.K()};this.active=!1;this.L=null;this.ya=[];this.va=this.qa=0;this.kc=null;this.D=[];this.fc=!1;this.Cb(a,c,d)};function oa(a){var c=1;a[0]&&(c=a[0].a.c);for(var c=A(0,c),d=0;d<a.length;d+=2){var b=a[d];b&&c.v(b.je(a[d+1]))}return c};K.prototype.X=function(a){null==a&&(a=this.J);if(!E(a)){if(this.Ua)this.L.X(a);else{a=D(a);for(var c=0;c<this.c;++c){var d=1<<c;a&d&&this.L.X(d,this.L)}this.qa^=a}this.K()}};H.prototype.X=function(a){0!=a&&(a==this.ea?this.If():a&this.aa?(this.i[0].X(a),this.i[1].X(a)):console.log("ERROR: bad condition (1) in NOT gate."))};
G.prototype.X=function(a){this.a.kc&&(bj=this.a.kc.cf());if(0!=a){var c=1<<this.c;if(0==(a&(1<<this.c)-1))console.log("ERROR: bad condition (2) in NOT gate.");else{if(this.j&&(this.j.Pd(a),!webgl_blocks.Y))return;for(var d,b,e,f=0,h=f+a;f<c;){for(var g=0;g<a;++g)b=2*f,e=2*h,d=this.values[b],this.values[b]=this.values[e],this.values[e]=d,d=this.values[b+1],this.values[b+1]=this.values[e+1],this.values[e+1]=d,f++,h++;f+=a;h+=a}this.j&&webgl_blocks.Y&&this.j.ta("NOT bit"+a,this.values)}}};
K.prototype.mc=function(a,c){this.ia(a,c);if(this.Aa)this.ka.mc(a),this.K();else{var d=ka(a),b=new C(a),e=new C(a);b.R(d[0],0);e.R(d[1],0);var d=new C(e),f=new C(b);d.v(c);f.v(c);this.G(b,d);this.G(e,f);this.G(b,d)}};K.prototype.ed=function(a,c){this.ia(a,c);var d=ka(a),b=new C(a),e=new C(a);b.R(d[0],0);e.R(d[1],0);var d=new C(e),f=new C(b);d.v(c);f.v(c);this.G(b,d);this.jc(e,f);this.G(b,d)};
K.prototype.G=function(a,c){if(!E(a))if(E(c))this.X(a);else if(this.I&&this.I.active){if(1==c.Jb())for(var d=c.P(),b=a.V(),e=a.P();e<=b;++e)a.O(e)&&this.I.G(null,d,e)}else{if(this.Ua)this.L.G(a,c);else{a=D(a);c=D(c);(c&this.va)!=c?this.ia(a):(this.qa&c)==c&&(this.qa^=a);for(d=0;d<this.c;++d)b=1<<d,a&b&&this.L.G(b,c,this.L);pa&&(qa(this,a),qa(this,c))}this.K()}};
H.prototype.G=function(a,c,d){0!=a&&(0==c?a&(this.ea|this.aa)?this.X(a):(a=this.i[0],this.i[0]=d.i[0],d.i[0]=a,a=this.i[1],this.i[1]=d.i[1],d.i[1]=a):c&this.ea?this.i[1].G(a,c&this.aa,d.i[1]):a==this.ea?this.i[0].G(a,c&this.aa,this.i[1]):(this.i[0].G(a,c&this.aa,d.i[0]),this.i[1].G(a,c&this.aa,d.i[1])))};
G.prototype.G=function(a,c,d){if(this.j&&(this.j.Pd(a,c,0,d.j),!webgl_blocks.Y))return;var b=1<<this.c,e;e=c;for(var f=a;f;)e&=~f,f>>=1;if(d!=this)for(f=e;f<b;++f)(f&c)==c&&(a=2*f,e=this.values[a],this.values[a]=d.values[a],d.values[a]=e,e=this.values[a+1],this.values[a+1]=d.values[a+1],d.values[a+1]=e);else for(var h=e,g=h+a;h<b;){for(var l=0;l<a;++l)(h&c)==c&&(d=2*h,f=2*g,e=this.values[d],this.values[d]=this.values[f],this.values[f]=e,e=this.values[d+1],this.values[d+1]=this.values[f+1],this.values[f+
1]=e),h++,g++;h+=a;g+=a}this.j&&webgl_blocks.Y&&this.j.ta("cNOT",this.values)};function qa(a,c){var d=L.Nd,b=L.Qf,e=a.xa=0,f=pa;pa=0;b?b(a,d,c):Math.random()<f&&(b=d*(2*Math.random()-1),d*=2*Math.random()-1,a.sa(c,180*b),a.Yb(c,180*d),a.xa+=Math.abs(b)+Math.abs(d),e+=2);e&&(a.xa/=e);pa=f}
K.prototype.sa=function(a,c){if(0!=c&&(null==a&&(a=this.J),!E(a)))if(this.I&&this.I.active)if(1==a.Jb()){for(var d=c;0>d;)d+=360;90*Math.floor(d/90)==d&&this.I.yc(null,a.P())}else{if(2==a.Jb()&&180==c){var d=a.P(),b=a.V();this.I.Ca(null,b);this.I.G(null,d,b);this.I.Ca(null,b)}}else this.Ua?this.L.sa(a,c):(a=D(a),a&=~(-1<<this.c),this.Aa?this.ka.yc(a,c):(d=c*Math.PI/180,this.L.sa(a,Math.sin(d),Math.cos(d)),pa&&qa(this,a))),this.K()};
H.prototype.sa=function(a,c,d){a&this.ea||this.i[0].sa(a&this.aa,c,d);this.i[1].sa(a&this.aa,c,d)};G.prototype.sa=function(a,c,d){if(this.j&&(this.j.Sf(a,0,c,d),!webgl_blocks.Y))return;var b=1<<this.c,e,f;if(0==a)for(var h,g=a;g<b;++g)h=2*g,e=this.values[h],f=this.values[h+1],this.values[h]=d*e+c*f,this.values[h+1]=d*f-c*e;else for(g=a;g<b;++g)(g&a)==a&&(h=2*g,e=this.values[h],f=this.values[h+1],this.values[h]=d*e+c*f,this.values[h+1]=d*f-c*e);this.j&&webgl_blocks.Y&&this.j.ta("phaseShift",this.values)};
K.prototype.pa=function(a,c,d,b){this.ia(a);if(!E(a)){if(this.Ua)this.L.pa(a,c,d,b);else{a=D(a);this.ia(a);for(var e=0;e<this.c;++e){var f=1<<e;a&f&&this.L.pa(f,c,d,b,this.L)}}this.K()}};H.prototype.pa=function(a,c,d,b,e){0!=a&&(a==this.ea?this.i[0].pa(a,c,d,b,this.i[1]):(this.i[0].pa(a,c,d,b,e.i[0]),this.i[1].pa(a,c,d,b,e.i[1])))};
G.prototype.pa=function(a,c,d,b,e){if(this.j&&(this.j.Rf(a,b,e.j),!webgl_blocks.Y))return;b=1<<this.c;if(e!=this)for(var f,h=0;h<b;++h)f=2*h,c(this.values,f,e.values,f,d);else for(var g=0,l=g+a;g<b;){for(var m=0;m<a;++m)f=2*g,h=2*l,c(this.values,f,this.values,h,d),g++,l++;g+=a;l+=a}this.j&&webgl_blocks.Y&&(this.j.ta("2x2 bit"+a,this.values),e!=this&&e.j.ta("2x2 bit (pairBlock)"+a,e.values))};
K.prototype.na=function(a,c,d,b,e){this.ia(a,c);if(!E(a))if(E(c))this.pa(a,d,b,e);else{if(this.Ua)this.L.na(a,c,d,b,e);else{a=D(a);c=D(c);this.ia(a);for(var f=0;f<this.c;++f){var h=1<<f;a&h&&this.L.na(h,c,d,b,e,this.L)}}this.K()}};H.prototype.na=function(a,c,d,b,e,f){0!=a&&(c&this.ea?this.i[1].na(a,c&this.aa,d,b,e,f.i[1]):a==this.ea?this.i[0].na(a,c&this.aa,d,b,e,this.i[1]):(this.i[0].na(a,c&this.aa,d,b,e,f.i[0]),this.i[1].na(a,c&this.aa,d,b,e,f.i[1])))};
G.prototype.na=function(a,c,d,b,e,f){e=1<<this.c;for(var h=c,g=a;g;)h&=~g,g>>=1;if(f!=this)for(;h<e;++h)(h&c)==c&&(a=2*h,d(this.values,a,f.values,a,b));else for(var g=h,l=g+a;g<e;){for(var m=0;m<a;++m)(g&c)==c&&(f=2*g,h=2*l,d(this.values,f,this.values,h,b)),g++,l++;g+=a;l+=a}this.j&&webgl_blocks.Y&&this.j.ta("c2x2",this.values)};function ra(a,c,d,b,e){var f=a[c],h=a[c+1],g=d[b],l=d[b+1];a[c]=(f+g)*e;a[c+1]=(h+l)*e;d[b]=(f-g)*e;d[b+1]=(h-l)*e}y=K.prototype;
y.Ca=function(a){null==a&&(a=this.J);if(this.I&&this.I.active)for(var c=a.V(),d=a.P();d<=c;++d)a.O(d)&&this.I.Ca(null,d);else c=1/Math.sqrt(2),this.pa(a,ra,c,[[{m:c,l:0},{m:c,l:0}],[{m:c,l:0},{m:-c,l:0}]]),pa&&qa(this,a)};y.gc=function(a,c){if(this.I&&this.I.active){if(null==a&&(a=this.J),E(c))for(var d=a.V(),b=a.P();b<=d;++b)a.O(b)&&this.I.Ca(null,b)}else d=1/Math.sqrt(2),this.na(a,c,ra,d,[[{m:d,l:0},{m:d,l:0}],[{m:d,l:0},{m:-d,l:0}]]),pa&&qa(this,a)};
function sa(a,c,d,b){a.ia(c,d);null==b&&(b=.5);null==c&&(c=a.J);var e=1;0>b&&(e=-1,b=-b);var f=Math.sqrt(b);b=Math.sqrt(1-b);e=[[{m:f,l:0},{m:0,l:e*b}],[{m:0,l:e*b},{m:f,l:0}]];a.na(c,d,ta,e,e)}y.Cd=function(a,c,d,b){this.ia(a,c);null==d&&(d=.5);null==a&&(a=this.J);if(this.Aa)a&&this.ka.sd(a,d),b&&this.ka.ie(b,d),this.K();else{var e=ka(a);b=new C(a);a=new C(a);b.R(e[0],0);a.R(e[1],0);var e=new C(a),f=new C(b);e.v(c);f.v(c);this.G(b,e);sa(this,a,f,d);this.G(b,e)}};
y.wc=function(a,c){if(this.Aa)this.ka.wc(a),this.K();else{this.write(a,0);this.write(c,0);var d=c.P(),b=c.V(),e=a.P(),f=a.V();d==b?(this.Ca(c),this.G(a,c)):(this.Ca(1<<d),this.X(1<<b),this.G(1<<b,1<<d),this.G(1<<e,1<<d),this.G(1<<f,1<<b))}};
y.Zc=function(a,c,d){this.ia(a,c);null==d&&(d=0);null==a&&(a=this.J);if(this.Aa)this.ka.Zc(a,d),this.K();else{var b=ka(a),e=new C(a);a=new C(a);e.R(b[0],0);a.R(b[1],0);var b=new C(a),f=new C(e);b.v(c);f.v(c);0>d?(this.write(a,-1),this.G(a,e)):(this.write(e,-1),this.G(e,a))}};
y.$c=function(a,c,d){this.ia(a,c);null==d&&(d=0);null==a&&(a=this.J);if(this.Aa)this.ka.$c(a,d),this.K();else{var b=ka(a),e=new C(a);a=new C(a);e.R(b[0],0);a.R(b[1],0);var b=new C(a),f=new C(e);b.v(c);f.v(c);0>d?(this.G(a,e),this.X(a),this.mb(a,0)):(this.G(e,a),this.X(e),this.mb(e,0))}};
function ta(a,c,d,b,e){var f=a[c],h=a[c+1],g=d[b],l=d[b+1];a[c]=e[0][0].m*f-e[0][0].l*h+e[0][1].m*g-e[0][1].l*l;a[c+1]=e[0][0].m*h+e[0][0].l*f+e[0][1].m*l+e[0][1].l*g;d[b]=e[1][0].m*f-e[1][0].l*h+e[1][1].m*g-e[1][1].l*l;d[b+1]=e[1][0].m*h+e[1][0].l*f+e[1][1].m*l+e[1][1].l*g}function ua(a,c,d,b,e){var f=e[0];e=e[1];var h=a[c],g=a[c+1],l=d[b],m=d[b+1];a[c]=e*h+f*m;a[c+1]=e*g-f*l;d[b]=e*l+f*g;d[b+1]=e*m-f*h}
function va(a,c,d,b,e){var f=e[0];e=e[1];var h=a[c],g=a[c+1],l=d[b],m=d[b+1];a[c]=e*h-f*l;a[c+1]=e*g-f*m;d[b]=e*l+f*h;d[b+1]=e*m+f*g}y.Yb=function(a,c){null==a&&(a=this.J);var d=c*Math.PI/180;this.pa(a,va,[Math.sin(d),Math.cos(d)],[[{m:0,l:0},{m:0,l:0}],[{m:0,l:0},{m:0,l:0}]])};y.rotate=K.prototype.Yb;y.Ud=function(a,c){null==a&&(a=this.J);var d=c*Math.PI/180;this.pa(a,ua,[Math.sin(d),Math.cos(d)],[[{m:0,l:0},{m:0,l:0}],[{m:0,l:0},{m:0,l:0}]])};
function wa(a,c,d,b,e){var f=a[c],h=a[c+1],g=d[b],l=d[b+1];0<e?(a[c]=.5*(f-h+g+l),a[c+1]=.5*(f+h-g+l),d[b]=.5*(f+h+g-l),d[b+1]=.5*(h-f+g+l)):(a[c]=.5*(f+h+g-l),a[c+1]=.5*(h-f+g+l),d[b]=.5*(f-h+g+l),d[b+1]=.5*(f+h-g+l))}y.jc=function(a,c){this.na(a,c,wa,1,[[{m:0,l:0},{m:0,l:0}],[{m:0,l:0},{m:0,l:0}]])};y.Kc=function(a,c){this.na(a,c,wa,-1,[[{m:0,l:0},{m:0,l:0}],[{m:0,l:0},{m:0,l:0}]])};
H.prototype.Db=function(a,c){if(0!=a)if(a&this.ea){var d=c>>this.c-1;this.i[1-d].Fa();this.i[d].Db(a&this.aa,c&this.aa)}else this.i[0].Db(a,c),this.i[1].Db(a,c)};G.prototype.Db=function(a,c){if(0!=a){if(this.j&&(this.j.Uf(a,c),!webgl_blocks.Y))return;for(var d=1<<this.c,b,e,f=0;f<this.c;++f){var h=1<<f;if(h&a)for(b=h&c?0:h;b<d;){for(var g=0;g<h;++g)e=2*(b+g),this.values[e]=0,this.values[e+1]=0;b+=2*h}}this.j&&webgl_blocks.Y&&this.j.ta("SetZeroMask",this.values)}};
function O(a){return a.read(a.J)}y=K.prototype;y.Fa=function(){this.L.Fa()};
y.read=function(a,c,d){null==a&&(a=this.J);if(E(a))return 0;if(!this.active)return console.log("register needs to be activated!"),0;if(this.I&&this.I.active){var b=a.P();d=a.V();for(c=new C(0,this.c);b<=d;++b)a.O(b)&&this.I.measure(null,b)&1&&c.R(b,1);this.K();return 32>=this.c?(a=D(c),c.bb(),a):c}if(this.Ua)return a=this.L.read(a),this.K(),a;a=D(a);var e;if((this.va&a)==a)return this.qa&a;e=0|this.qa&this.va;for(var b=a&~this.va,f=0;f<this.c;++f){var h=1<<f;if(b&h){var g=this.Pa(h),l=1;0<g&&(l=Math.random(),
c?l=1:d&&(l=0),l<=g?(e|=h,l=Math.sqrt(g)):l=Math.sqrt(1-g));this.L.Db(h,e);xa(this,l)}}this.Wd(a,e);this.K();return this.qa&a};function ya(a,c){a.write(a.J,c)}y.write=function(a,c){null==a&&(a=this.J);var d=ea(this.read(a));d.od(c);d.la(a);d.Uc()||this.X(d);d.bb();this.K()};y.mb=function(a,c){null==a&&(a=this.J);this.Aa?this.ka.mb(a,c):this.read(a,0==c,1==c);this.K()};
y.Bc=function(a){null==a&&(a=this.J);if(this.Aa)this.ka.Bc(a);else{a=1<<a.P()|1<<a.V();for(var c=0;c<this.$a;++c)0!=(c&a)&&(c&a)!=a||this.Ea(c,0,0);xa(this)}this.K()};y.hb=function(){return this.L.hb()};H.prototype.hb=function(){return this.i[0].hb()+this.i[1].hb()};G.prototype.hb=function(){if(this.j){var a=this.j.kf(0);if(!webgl_blocks.Y)return a}for(var c=0,d=1<<this.c,b,d=2*d,e=0;e<d;++e)b=this.values[e],c+=b*b;this.j&&webgl_blocks.Y&&this.j.ta("totalLengthSquared",null,a,c);return c};
K.prototype.Pa=function(a){return this.L.Pa(a)};H.prototype.Pa=function(a){return a==this.ea?this.i[1].hb():this.i[0].Pa(a)+this.i[1].Pa(a)};G.prototype.Pa=function(a){var c=0,d=1<<this.c,b,e,f=0;if(this.j){var h=this.j.kf(a);if(!webgl_blocks.Y)return h}for(var g=a;g<d;g+=2*a)for(var f=f+a,l=0;l<a;++l)e=2*f,b=this.values[e],e=this.values[e+1],c+=b*b+e*e,f++;this.j&&webgl_blocks.Y&&this.j.ta("peekProbability",null,h,c);return c};
K.prototype.Qa=function(a,c,d){null==a&&(a="");null==c&&(c=0);null==d&&(d=1<<this.c);for(a="QReg: "+a+" ";c<d;++c){var b=this.ja(c);if(0!=b.x||0!=b.y)a+="["+c+"]="+b.x.toFixed(6)+","+b.y.toFixed(6)+" "}console.log(a)};K.prototype.ja=function(a){return(this.qa&this.va)!=(a&this.va)?new I(0,0):this.L.ja(a)};H.prototype.ja=function(a){return a&this.ea?this.i[1].ja(a&this.aa):this.i[0].ja(a&this.aa)};
G.prototype.ja=function(a){if(this.j){var c=this.j.Wf(a);if(!webgl_blocks.Y)return c}a*=2;value=new I(this.values[a],this.values[a+1]);this.j&&webgl_blocks.Y&&(this.j.ta("peekComplexValue.x",null,c.x,value.x),this.j.ta("peekComplexValue.y",null,c.y,value.y));return value};K.prototype.Ea=function(a,c,d){this.va=0;this.L.Ea(a,c,d)};H.prototype.Ea=function(a,c,d){a&this.ea?this.i[1].Ea(a&this.aa,c,d):this.i[0].Ea(a&this.aa,c,d)};
G.prototype.Ea=function(a,c,d){a*=2;this.values[a]=c;this.values[a+1]=d;this.j&&webgl_blocks.Y&&this.j.ta("pokeComplexValue",this.values)};function xa(a,c){null==c&&(c=Math.sqrt(a.L.hb()));0==c?a.L.Ob(0):1!=c&&a.L.$b(1/c)};function I(a,c){this.x=a;this.y=c;this.length=function(){return Math.sqrt(this.x*this.x+this.y*this.y)};this.Bf=function(){return this.x*this.x+this.y*this.y};this.normalize=function(){var a=this.length();0<a&&(this.x/=a,this.y/=a)}}function Q(a,c,d,b,e,f){var h;null==e&&(e=0);null==f&&(f=360);null==h&&(h=!0);e=e*Math.PI/180;f=f*Math.PI/180;a.beginPath();a.arc(c,d,b,e,f,h);a.closePath();a.fill()}
function R(a,c,d,b,e,f){var h;null==e&&(e=0);null==f&&(f=360);null==h&&(h=!0);e=e*Math.PI/180;f=f*Math.PI/180;a.beginPath();a.arc(c,d,b,e,f,h);a.closePath();a.stroke()}function za(a){var c=new Image;c.src=a;c.onload=Aa;return c}function Ba(a,c){this.x=a;this.y=c;this.count=0;return this}
function Ca(a,c,d,b){this.a=a;this.g=c;this.scale=1;this.u=new I(d.x,d.y);this.size=new I(1,1);this.sc=new I(0,0);this.vb=this.wb=!1;this.Re=new za(b);a.D.push(this);c.D.push(this);this.N=function(){var b=this.g.canvas.getContext("2d");b.save();b.save();var a=this.u.x+.5*this.size.x,c=this.sc.y,d=this.sc.x;b.fillStyle="#ffffff";b.fillRect(this.u.x,this.u.y,this.size.x,this.size.y);b.fillRect(a-.5*d,this.u.y+this.size.y,d,c);b.restore();a=this.Re;if(null!=a&&0<a.width){this.size=new I(a.width*this.scale,
a.height*this.scale);try{b.drawImage(a,this.u.x,this.u.y,this.size.x,this.size.y)}catch(m){}var a=.5*this.size.x,c=.5*this.size.y,d=this.u.x+a,l=this.u.y+c;this.vb&&this.wb&&(b.save(),b.fillStyle="#ffffff",b.globalAlpha=.5,Q(b,d,l,a-4,c-4),b.restore());if(this.vb||this.wb)b.font="9px sans-serif",b.textAlign="center",b.textBaseline="top",b.fillText(this.label,d,this.u.y+this.size.y),this.sc.x=b.measureText(this.label).width+2,this.sc.y=11}b.restore()};this.K=function(){this.N()};this.message=function(){};
this.sb=function(){};this.Hc=function(b,a){var c=.5*this.size.x,d=b-c,l=a-c;return this.wb=d*d+l*l<=c*c};this.Qb=function(b,a){var c=!1;this.Hc(b,a)&&(this.vb=!0,this.N(),c=!0);return c};this.Sb=function(b,a){var c=this.wb,d=this.vb;this.Hc(b,a)&&this.vb&&this.sb(b,a);this.vb=!1;(c||d)&&this.N();return!1};this.Rb=function(b,a){var c=this.wb;this.Hc(b,a)!=c&&this.N();return!1}}
function Da(a,c){var d=new I(0,0);this.Bb=null;this.a=a;this.g=c;this.u=new I(d.x,d.y);this.width=this.g.canvas.width-d.x;this.height=this.g.canvas.height-d.y;this.qc=this.visible=!0;this.margin={x:10,y:30};this.ad=[];this.rd=14;this.Hb=this.rd+10;this.scale=.75;this.wa=this.$=this.Gc=1;this.he=!1;this.a.D.push(this);c.D.push(this);this.me=function(){this.scale=this.Gc;L&&L.qe&&(this.scale=L.qe);this.scale*=this.$;this.ma=50;this.ic=2.5*this.ma;this.hc=2.5*this.ma;for(var b=5,a=this.g.D,c=0;c<a.length&&
a[c]!=this;++c)b+=a[c].height+5;this.u.y=b;if(!this.qc||this.u.x>=this.g.canvas.width||this.u.y>=this.g.canvas.height)this.visible=!1;else{this.visible=!0;this.width=this.g.canvas.width-this.u.x;this.height=this.g.canvas.height-this.u.y;b=this.$a;this.Na&&(b=1<<this.Na.H);this.Za=this.width/(this.ic*this.scale);this.yb=this.height/(this.hc*this.scale);a=-1;for(c=0;0>a;++c)this.Za<.75*(1<<c+1)&&(a=c);this.Za=1<<a;this.Za>b&&(this.Za=b);this.yb>Math.ceil(b/this.Za)&&(this.yb=Math.ceil(b/this.Za));this.yb=
Math.ceil(this.yb);c=this.margin.x+this.ic*this.Za/this.scale;b=this.margin.y+this.hc*this.yb*this.scale;this.height>b&&(this.height=b);this.width>c&&(this.width=c);this.collapsed&&(this.height=this.Hb)}};this.pf=function(){var b=0;this.g.rc.options[b++]=new Option("raw register","(raw)");for(var a=this.a.Qe(),d=0;d<a.length;++d)0<a[d].text.length&&"("!=a[d].text[0]&&(this.g.rc.options[b++]=a[d]);c.rc.options.length=b;for(c.rc.onchange=this.vf;this.g.D.length<this.a.ya.length+1;)new Da(this.a,c);
var a=this.a.ya,d=this.g.D,b=0,h;for(h in a){var g=a[h];d[b].qc=!0;d[b].Na=g;d[b].collapsed=!0;b++}d[b].qc=!0;d[b].Na=null;d[b].collapsed=!1;for(b++;b<d.length;)d[b++].qc=!1};this.vf=function(){this.ad=[];Ea()};this.g.qd=.3;this.g.Ma=0;this.g.pd=30;this.g.Ta=null;this.Cc=function(){this.pf()};this.Le=function(b,a,c){var d=a?a.length():0,g=1E-6>d,l=this.ma*d*this.wa;b.fillStyle="#ffffff";Q(b,0,0,this.ma);if(!g){if(!L.Of||g||c)b.fillStyle="#b8cce4";else{var m=127.5*(a.x/d+1);b.fillStyle="RGB("+m.toFixed(0)+
", "+(255-m).toFixed(0)+", "+(127.5*(a.y/d+1)).toFixed(0)+")"}Q(b,0,0,l)}b.lineWidth=2;b.strokeStyle="#444";R(b,0,0,this.ma);if(c){b.lineWidth=.25;b.strokeStyle="black";b.beginPath();for(d=0;d<c.length;++d)m=c[d].length(),b.moveTo(0,0),b.lineTo(c[d].y*this.ma/m,-c[d].x*this.ma/m);b.stroke()}else 0<l&&!g&&(b.lineWidth=.25,b.strokeStyle="black",b.beginPath(),b.moveTo(0,0),b.lineTo(a.y*this.ma/d,-a.x*this.ma/d),b.stroke());0<l&&(b.lineWidth=3,b.strokeStyle="#548dd4",R(b,0,0,l),c||g||(b.beginPath(),b.lineTo(0,
0),b.lineTo(a.y*this.wa*this.ma,-a.x*this.wa*this.ma),b.stroke()))};this.Me=function(b,a,c){var d=0;a=a.Bf();b.strokeStyle="#000000";b.fillStyle="#000000";b.font="bold 20px sans-serif";b.textAlign="center";b.textBaseline="top";var g=d=0+1.025*this.ma;b.fillText(c,0,g);d=b.measureText(c).width;c=-2-d/2;var d=2+d/2,l=d+4.5,g=g+4,m=g+9,n=g+18;b.beginPath();b.moveTo(c,g);b.lineTo(c,n);b.moveTo(d,g);b.lineTo(l,m);b.lineTo(d,n);b.stroke();d=0+.5*this.ma;b.globalAlpha=.25;b.fillText((100*a).toFixed(1)+"%",
0,d);b.globalAlpha=1};this.Ne=function(b){b.save();b.fillStyle="white";b.fillRect(this.u.x,this.u.y,this.width,this.height);b.lineWidth=1;b.beginPath();b.rect(this.u.x,this.u.y,this.width,this.height);b.clip();var a="full state";this.Na&&(a=this.Na.name);b.font="bold "+this.rd+"px sans-serif";b.textAlign="left";b.textBaseline="top";var c=this.u.x,d=this.u.y;b.fillStyle="#def";b.fillRect(c,d,this.width,this.Hb);c+=this.Hb;b.fillStyle="black";b.fillText(a,c,d+5);var c=this.Hb/2,d=this.Hb/4,a=.6*d,d=
1*d,g=this.u.x+c,c=this.u.y+c;b.strokeStyle="black";b.lineWidth=1;b.beginPath();this.collapsed?(b.moveTo(g-a,c-d),b.lineTo(g-a,c+d),b.lineTo(g+a,c),b.lineTo(g-a,c-d)):(b.moveTo(g-d,c-a),b.lineTo(g+d,c-a),b.lineTo(g,c+a),b.lineTo(g-d,c-a));b.stroke();b.lineWidth=1;this.se=g-this.u.x;this.te=c-this.u.y;b.restore();if(!this.collapsed){b.save();b.translate(this.u.x+this.margin.x,this.u.y+this.margin.y);b.scale(this.scale,this.scale);b.translate(this.ma,this.ma);var l,m=new I(0,0);b.lineWidth=1;a=this.yb;
c=this.Za;d=this.a;this.Bb&&this.Bb.valid&&(d=this.Bb);var n=0,u=0,n=n=0,g=!1,u=0;0<this.g.Ma&&(g=!0,n=this.g.Ma/this.g.qd,u=Math.sin(n*Math.PI),n=Math.cos(n*Math.PI),u*=.15,n=.5*(1-n));if(this.he){this.wa=1;for(var k=0,v=0;v<a;++v)for(var r=0;r<c;++r)m=v*c+r,m<this.$a&&(m=d.ja(m),k=Math.max(Math.abs(m.x),Math.max(Math.abs(m.y),k)));0<k&&(this.wa=1/k)}k=this.$a;this.Na&&(k=1<<this.Na.H);for(v=0;v<a;++v){b.save();for(r=0;r<c;++r)if(m=v*c+r,m>=k)v=a,r=c;else{var p=l=null;this.Na?(p=[],l=this.Na.jf(m,
p),1==p.length?(l=p[0],p=null):l=new I(0,Math.sqrt(l))):l=d.ja(m);this.Mf&&!g&&(this.ad[m]=l);b.save();if(g)if(!this.g.Ta||"not"!=this.g.Ta.b&&"cnot"!=this.g.Ta.b){var t=this.ad[m];null!=t&&l&&(l.x=n*t.x+(1-n)*l.x,l.y=n*t.y+(1-n)*l.y)}else{var w=this.g.Ta.o.Mb(0),t=this.g.Ta.h.Mb(0);if(E(this.g.Ta.o)||(m&w)==w){for(var x=w=0,z=0;z<this.a.c;++z){var B=1<<z;if(B&t){var J=1;m&B&&(J=-1);B>=c?x+=B/c*this.hc*J:w+=J*this.ic*B}}b.translate(n*w+u*x,n*x+u*w)}}this.Le(b,l,p);b.restore();this.Me(b,l,m);b.translate(this.ic,
0)}b.restore();b.translate(0,this.hc)}this.Mf=g;b.restore()}};this.N=function(){this.$a=this.Bb&&this.Bb.valid?1<<this.Bb.H:1<<this.a.c;this.me();if(this.visible){var b=this.g.canvas.getContext("2d");this.Ne(b)}};this.K=function(){this.N()};this.message=function(){};this.Xc=function(b){1==b.ctrlKey?(b=b.deltaY,0<b&&(this.$*=.9),0>b&&(this.$*=1.1),.1>this.$&&(this.$=.1),3<this.$&&(this.$=3),this.g.N()):1==b.shiftKey&&(b=b.deltaX,0<b&&(this.wa*=.9),0>b&&(this.wa*=1.1),1>this.wa&&(this.wa=1),10<this.wa&&
(this.wa=10),this.g.N());return!1};this.Qb=function(b,a){var c=b-this.se,d=a-this.te;return 225>c*c+d*d?(this.collapsed=!this.collapsed,this.g.N(),!0):!1};this.Sb=function(){return!1};this.Rb=function(){return!1}};BlockJob=function(){this.Af=function(){this.Lb=this.Fb=!1};this.start=function(){}};var Fa=null,L={},pa,Ga,Ha;
function Ia(a,c,d,b,e,f){this.a=null;this.b=a;null==c&&(c=0);null==d&&(d=0);null==f&&(f=0);this.h=new C(c);this.o=new C(d);f&&(this.Ha=new C(f));this.Ia=e;if("write"==a||"postselect"==a)this.dc=d,this.o.set(0);this.T=b;this.rb=[];this.nc=this.jb=0;this.Lb=this.Fb=!1;this.Qc=function(c,d){null==d&&(d=1);this.a=c;this.nc=this.jb=0;c.kc=this;this.Fb=!0;this.Lb=!1;this.xa=this.a.xa=0;if("not"==a)c.X(this.h);else if("cnot"==a)c.G(this.h,this.o);else if("exchange"==a)c.mc(this.h,this.o);else if("hadamard"==
a)c.gc(this.h,this.o);else if("chadamard"==a)c.gc(this.h,this.o);else if("rotatex"==a)c.Yb(this.h,b*d);else if("crotatex"==a){var e=b*d*Math.PI/180;c.na(this.h,this.o,va,[Math.sin(e),Math.cos(e)],[[{m:0,l:0},{m:0,l:0}],[{m:0,l:0},{m:0,l:0}]])}else if("rotatey"==a)c.Ud(this.h,b*d);else if("crotatey"==a)e=b*d*Math.PI/180,c.na(this.h,this.o,ua,[Math.sin(e),Math.cos(e)],[[{m:0,l:0},{m:0,l:0}],[{m:0,l:0},{m:0,l:0}]]);else if("crootnot"==a&&0<d||"crootnot_inv"==a&&0>d)c.jc(this.h,this.o);else if("crootnot_inv"==
a&&0<d||"crootnot"==a&&0>d)c.Kc(this.h,this.o);else if("rootexchange"==a&&0<d||"rootexchange_inv"==a&&0>d)c.ed(this.h,this.o);else if("rootexchange_inv"==a&&0<d||"rootexchange"==a&&0>d)c.ed(this.h,this.o);else if("noise"==a)c.sa(this.h,this.T);else if("phase"==a)c.sa(this.o,this.T*d);else if("optical_phase"==a){var e=this.o,f=this.T*d;c.ia(e);null==e&&(e=c.J);f=f*Math.PI/180;f=[[{m:Math.cos(f),l:-Math.sin(f)},{m:0,l:0}],[{m:0,l:0},{m:1,l:0}]];c.pa(e,ta,f,f)}else if("optical_beamsplitter"==a){var e=
this.h,n=this.T*d;c.ia(e);null==n&&(n=.5);null==e&&(e=c.J);f=1;0>n&&(f=-1,n=-n);var u=Math.sqrt(n),n=Math.sqrt(1-n),f=[[{m:u,l:0},{m:0,l:f*n}],[{m:0,l:f*n},{m:u,l:0}]];c.pa(e,ta,f,f)}else if("coptical_beamsplitter"==a)sa(c,this.h,this.o,this.T*d);else if("read"==a&&0<d)this.bd=c.read(this.h,!1,!1);else if("write"==a&&0<d)c.write(this.h,this.dc);else if("postselect"==a&&0<d)c.mb(this.h,this.dc);else if("postselect_qubit_pair"==a&&0<d)c.Bc(this.h);else if("dual_rail_beamsplitter"==a)c.Cd(this.h,this.o,
this.T*d,this.Ha);else if("pair_source"==a)c.wc(this.h,this.o,0);else if("polarization_grating_in"==a)c.Zc(this.h,this.o,this.T*d);else if("polarization_grating_out"==a)c.$c(this.h,this.o,this.T*d);else if("discard"!=a&&"nop"!=a)if("start_photon_sim"==a)c.Df(this.h,this);else if("stop_photon_sim"==a)c.Hf();else if("start_chp_sim"==a)c.Cf(this.h,this);else if("stop_chp_sim"==a)c.Gf();else if("peek"==a){e=this.h.V();f=this.h.P();this.nb=[];for(u=0;u<f;++u)this.nb.push(null);for(u=f;u<=e;++u)this.nb.push(c.Pa(1<<
u))}this.xa=this.a.xa;this.finish()};this.cf=function(){var b;this.jb<this.rb.length?b=this.rb[this.jb]:(b=new BlockJob,this.rb.push(b));this.jb++;b.Af()};this.wf=function(){if(this.Ye())return 0;for(var b=this.nc;b<this.jb;++b)if(this.rb[b].Fb)return this.rb[b].start(),this.nc=b+1,this.nc-b;this.yf();return 0};this.Ye=function(){return!this.a};this.yf=function(){this.Lb=this.Fb=!0;this.a=this.a.kc=null;this.jb=0};this.finish=function(){for(;0<this.wf(););};this.N=function(b,a,c,d,e,f,k,v){var r;
b.lineWidth=2;b.fillStyle="white";if("cnot"==this.b||"not"==this.b)Q(b,a,c,d),b.lineWidth=2,b.beginPath(),b.lineTo(a-d,c),b.lineTo(a+d,c),b.lineTo(a,c),b.lineTo(a,c-d),b.lineTo(a,c+d),b.stroke(),R(b,a,c,d);else if("noise"==this.b)b.fillStyle="#f00",Q(b,a,c,.4*d),b.fillStyle="#fff";else if("peek"==this.b)b.lineWidth=2,b.beginPath(),b.moveTo(a,c),b.lineTo(a,c-.2*d),b.stroke(),this.nb&&this.nb.length>e&&null!=this.nb[e]&&(r=this.nb[e],e=r.toFixed(1),k=r.toFixed(3),r="",r=parseFloat(k)==parseFloat(e)?
r+e:r+k,Ja(b,r,a,c-.2*d,10,"","#48f","center","bottom"));else if("stop_photon_sim"==this.b)e=.5*f.f,b.fillStyle="#4f8",b.globalAlpha=.25,k-=f.Ff,b.fillRect(-k,c-e,k,2*e),b.globalAlpha=.75,b.fillRect(a-.1*d,c-.5*f.f,.2*d,f.f),b.globalAlpha=1;else if("start_photon_sim"==this.b)b.fillStyle="#4f8",b.globalAlpha=.25,f.Ff=k,b.globalAlpha=.75,b.fillRect(a-.1*d,c-.5*f.f,.2*d,f.f),b.globalAlpha=1;else if("stop_chp_sim"==this.b)e=.5*f.f,b.fillStyle="#C38EFF",b.globalAlpha=.25,k-=f.Ef,b.fillRect(-k,c-e,k,2*
e),b.globalAlpha=.75,b.fillRect(a-.1*d,c-.5*f.f,.2*d,f.f),b.globalAlpha=1;else if("start_chp_sim"==this.b)b.fillStyle="#C38EFF",b.globalAlpha=.25,f.Ef=k,b.globalAlpha=.75,b.fillRect(a-.1*d,c-.5*f.f,.2*d,f.f),b.globalAlpha=1;else if("postselect_qubit_pair"==this.b){k=d/.8;var p=this.h.V();r=this.h.P();if(p==r+1){var p=3,t=1;e==r&&(b.save(),b.scale(1,p),b.lineWidth=1,b.strokeStyle="#08f",R(b,a,(c+.5*t*f.f)/p,.5*k),b.restore())}else p=3,b.save(),b.scale(1,p),b.lineWidth=1,b.strokeStyle="#08f",R(b,a,
c/p,.25*k),b.restore()}else if("pair_source"==this.b)p=this.h.V(),r=this.h.P(),b.fillStyle="#f20",p==r?Q(b,a,c,.3*f.f):e==r?Q(b,a,c,.3*f.f,0,180):e==p&&Q(b,a,c,.3*f.f,180,0);else if("exchange"==this.b||"rootexchange"==this.b||"rootexchange_inv"==this.b||"dual_rail_beamsplitter"==this.b||"polarization_grating_in"==this.b||"polarization_grating_out"==this.b)if(p=this.h.V(),r=this.h.P(),p==r+1){yd=2*d*f.lc;k=d/.8;b.lineWidth=1;b.fillStyle="white";b.strokeStyle="white";b.fillRect(a-d,c-1,2*d,2);b.strokeRect(a-
d,c-1,2*d,2);b.fillRect(a-1,c-d,2,2*d);b.strokeRect(a-1,c-d,2,2*d);b.strokeStyle="black";b.beginPath();if("dual_rail_beamsplitter"==this.b)t=-1,e==r&&(t=1),b.moveTo(a-k,c),b.lineTo(a-.7*k,c+.2*t*k),b.lineTo(a-.5*k,c+.6*t*k),b.lineTo(a-.3*k,c+.8*t*k),b.lineTo(a+.3*k,c+.8*t*k),b.lineTo(a+.5*k,c+.6*t*k),b.lineTo(a+.7*k,c+.2*t*k),b.lineTo(a+k,c);else if("polarization_grating_in"==this.b||"polarization_grating_out"==this.b){t=f=-1;e==r&&(t=1);"polarization_grating_in"==this.b&&(f=1);e==r&&0<=this.T?(b.moveTo(a-
1*f*k,c-0*t*k),b.lineTo(a-.5*f*k,c+.5*t*k)):e==p&&0>this.T&&(b.moveTo(a-1*f*k,c-0*t*k),b.lineTo(a-.5*f*k,c+.5*t*k));b.moveTo(a-1*k,c+1*t*k);b.lineTo(a+0*k,c-0*t*k);b.lineTo(a+1*k,c+1*t*k);b.moveTo(a+0*f*k,c-0*t*k);b.lineTo(a+1*f*k,c+0*t*k);b.lineTo(a+.5*f*k,c+.5*t*k);b.stroke();b.strokeStyle="#000";b.lineWidth=.5;b.beginPath();for(f=-.8;1>f;f+=.3)0>f?b.moveTo(a+f*k,c-f*t*k):b.moveTo(a+f*k,c+f*t*k),b.lineTo(a+f*k,c+1*t*k),0>f&&(b.moveTo(a+f*k,c-f*t*k),b.lineTo(a-f*k,c-f*t*k));b.stroke();b.beginPath();
b.strokeStyle="black";b.lineWidth=1}else if("polarization_grating_out"==this.b)t=-1,e==r&&(t=1),b.moveTo(a-k,c),b.lineTo(a-.7*k,c+.2*t*k),b.lineTo(a-.5*k,c+.6*t*k),b.lineTo(a-.3*k,c+.8*t*k);else{t=c-k;e==r&&(t=c+k);yd=2*d*f.lc;var w=f.Ga[v].O(r);f=f.Ga[v].O(p);v=w;var x=f;e==p&&(x=w,v=f);v&&(b.moveTo(a-k,c),b.lineTo(0,t));x&&(b.moveTo(0,t),b.lineTo(a+k,c))}b.stroke();E(this.o)||(b.lineWidth=2,b.beginPath(),e==r?(b.moveTo(a-.5*k,c+.5*k),b.lineTo(0,c+1*k),b.lineTo(a+.5*k,c+.5*k)):(b.moveTo(a-.5*k,c-
.5*k),b.lineTo(0,c-1*k),b.lineTo(a+.5*k,c-.5*k)),b.stroke(),f=this.o.V(),t=this.o.P(),w=!1,e==r?t<r&&(w=!0):(f>p&&(w=!0),b.fillStyle="black",Q(b,a,c-k,.25*k)),w&&(b.lineWidth=2,b.strokeStyle="black",b.beginPath(),b.moveTo(a,c+k),b.lineTo(a,c-k),b.stroke()));e!=p||"rootexchange"!=this.b&&"rootexchange_inv"!=this.b||(b.save(),b.translate(a+k,c-k),b.scale(.75,.75),b.lineWidth=1,b.fillStyle="white",b.fillRect(-d,-d,2*d,2*d),b.strokeRect(-d,-d,2*d,2*d),b.lineWidth=2,b.beginPath(),e=.4*d,k=.6*d,"rootexchange_inv"==
this.b&&(e=-e),b.lineTo(-2*e,.25*k),b.lineTo(-e,k),b.lineTo(0,-k),b.lineTo(2*e,-k),b.stroke(),b.restore())}else{if(k=.75*d,"dual_rail_beamsplitter"==this.b?(b.strokeStyle="white",b.lineWidth=2,b.beginPath(),b.moveTo(a-k,c),b.lineTo(a+k,c),b.stroke(),b.strokeStyle="black",b.lineWidth=2,b.beginPath(),b.moveTo(a-k,c),e==p?(b.lineTo(a-.5*k,c-.7*k),b.lineTo(a+.5*k,c-.7*k)):(b.lineTo(a-.5*k,c+.7*k),b.lineTo(a+.5*k,c+.7*k)),b.lineTo(a+k,c),b.stroke()):(e=0,f.Ga[v].O(p)&&e++,f.Ga[v].O(r)&&e++,2!=e&&E(this.o)||
(b.lineWidth=2,b.beginPath(),b.moveTo(a-k,c-k),b.lineTo(a+k,c+k),b.moveTo(a-k,c+k),b.lineTo(a+k,c-k),b.stroke())),"rootexchange"==this.b||"rootexchange_inv"==this.b)b.save(),b.translate(a+k,c),b.scale(.75,.75),b.lineWidth=1,b.fillStyle="white",b.fillRect(-d,-d,2*d,2*d),b.strokeRect(-d,-d,2*d,2*d),b.lineWidth=2,b.beginPath(),e=.4*d,k=.6*d,"rootexchange_inv"==this.b&&(e=-e),b.lineTo(-2*e,.25*k),b.lineTo(-e,k),b.lineTo(0,-k),b.lineTo(2*e,-k),b.stroke(),b.restore()}else if("chadamard"==this.b||"hadamard"==
this.b)b.lineWidth=1,b.fillStyle="white",b.fillRect(a-d,c-d,2*d,2*d),b.strokeRect(a-d,c-d,2*d,2*d),b.lineWidth=2,b.beginPath(),e=.4*d,k=.6*d,b.lineTo(a-e,c-k),b.lineTo(a-e,c+k),b.lineTo(a-e,c),b.lineTo(a+e,c),b.lineTo(a+e,c-k),b.lineTo(a+e,c+k),b.stroke();else if("optical_beamsplitter"==this.b||"coptical_beamsplitter"==this.b)b.lineWidth=1,b.fillStyle="white",b.fillRect(a-d,c-d,2*d,2*d),b.lineWidth=1,b.beginPath(),e=.5*d,k=.5*d,b.moveTo(a-d,c-k),b.lineTo(a-e,c-k),b.lineTo(a+e,c+k),b.lineTo(a+d,c+
k),b.moveTo(a-d,c+k),b.lineTo(a-e,c+k),b.lineTo(a+e,c-k),b.lineTo(a+d,c-k),b.stroke(),b.lineWidth=1,b.beginPath(),b.moveTo(a-e,c),b.lineTo(a+e,c),b.stroke();else if("crotatex"==this.b||"rotatex"==this.b||"crotatey"==this.b||"rotatey"==this.b)b.lineWidth=1,b.fillStyle="white",b.fillRect(a-d,c-d,2*d,2*d),b.strokeRect(a-d,c-d,2*d,2*d),b.lineWidth=2,b.beginPath(),e=.4*d,k=.6*d,a-=1*e,e*=.7,b.moveTo(a-e,c+k),b.lineTo(a-e,c-k),b.lineTo(a+.8*e,c-k),b.lineTo(a+e,c-.75*k),b.lineTo(a+e,c-.25*k),b.lineTo(a+
.8*e,c),b.lineTo(a-e,c),b.lineTo(a+0*e,c),b.lineTo(a+e,c+k),b.stroke(),e=.4*d,a+=2*e,e*=.9,c+=1*e,k*=.7,b.lineWidth=1,b.beginPath(),"crotatex"==this.b||"rotatex"==this.b?(b.moveTo(a-e,c-k),b.lineTo(a+e,c+k),b.moveTo(a+e,c-k),b.lineTo(a-e,c+k)):(b.moveTo(a+e,c-k),b.lineTo(a,c),b.moveTo(a-e,c-k),b.lineTo(a,c),b.lineTo(a,c+k)),b.stroke();else if("crootnot"==this.b||"crootnot_inv"==this.b)b.lineWidth=1,b.fillStyle="white",b.fillRect(a-d,c-d,2*d,2*d),b.strokeRect(a-d,c-d,2*d,2*d),b.lineWidth=2,b.beginPath(),
e=.4*d,k=.6*d,"crootnot_inv"==this.b&&(e=-e),b.lineTo(a-2*e,c+.25*k),b.lineTo(a-e,c+k),b.lineTo(a,c-k),b.lineTo(a+2*e,c-k),b.stroke();else if("read"==this.b||"postselect"==this.b){b.fillStyle="white";b.lineWidth=1;b.fillRect(a-.5*d,c-d,1.5*d,2*d);k=.99*d;if("postselect"==this.b||Ga&&null!=this.bd)r=this.dc,b.fillStyle="#ddd","read"==this.b&&(b.strokeStyle="#48f",r=(r=this.bd)?r.da?r.O(e):r>>e&1:0),r&&(b.fillStyle="#ffa"),Q(b,a-.5*d,c,k,90,270),b.fillStyle="white",b.lineWidth=1.5,r?(b.beginPath(),
b.moveTo(a,c-.4*k),b.lineTo(a,c+.4*k),b.stroke()):R(b,a,c,.3*k,0,360),b.strokeStyle="black",b.lineWidth=.25;b.beginPath();k=.99*d;b.moveTo(a-.5*d,c-k);b.lineTo(a-.5*d,c+k);b.stroke();R(b,a-.5*d,c,k,90,270);b.lineWidth=1}else"write"==this.b&&(b.fillStyle="white",b.lineWidth=1,k=.5*d,r=.7*d,Ha&&fa(this.dc,e)&&(b.fillStyle="#ffa"),b.lineWidth=1,f.Bd?(p=a+.4*d,t=c-2.5*d*f.lc,f=c+2.5*d*f.lc,k*=.8,r*=.5,b.beginPath(),b.moveTo(p-k,t+r),b.lineTo(p+d,t),b.lineTo(p-k,t-r),b.moveTo(p-k,f+r),b.lineTo(p+d,f),
b.lineTo(p-k,f-r)):(b.beginPath(),b.moveTo(a-k,c+r),b.lineTo(a+d,c),b.lineTo(a-k,c-r)),b.fill(),b.lineWidth=1,b.strokeStyle="black",b.stroke(),Ha&&(b.lineWidth=1.5,b.strokeStyle="#48f",fa(this.dc,e)?(b.beginPath(),b.moveTo(a-1*k,c-.7*k),b.lineTo(a-1*k,c+.7*k),b.stroke()):R(b,a-1*k,c,.5*k,0,360),b.strokeStyle="black",b.lineWidth=1));0<this.xa&&L.Oe&&(e=this.xa/L.Nd,k=b.createRadialGradient(a,c,0,a,c,2.25*d),k.addColorStop(0,"rgba(255,100,0,255)"),k.addColorStop(1,"rgba(255,0,0,0"),b.globalAlpha=e,
b.fillStyle=k,Q(b,a,c,2.25*d),b.fillStyle="#fff",b.globalAlpha=1)};this.Ee=function(b,a,c){b.lineWidth=1;b.fillStyle="gray";for(var d=0;d<this.jb;++d){var e=this.rb[d];this.Fb&&!this.Lb&&(b.fillStyle=e.Lb?"green":e.Fb?"yellow":"red");b.beginPath();b.lineTo(0-c,a+4*d);b.lineTo(0+c,a+4*d);b.stroke()}}};function Ka(a,c){document.getElementById(a).style.display=c?"block":"none"};var La=null;var Ma=[],S=null,Na=0,Oa="move",Qa=null,Ra=null,Sa=null,Ta=null;
function Ua(a,c){this.canvas=a;this.ba=c;c.g=this;this.D=[];this.Ya=this.Xa=0;this.Oa=16;this.canvas&&(this.canvas.g=this);this.Ad=this.zd=this.Pc=this.Oc=0;this.N=function(){if(this.canvas){var a=this.canvas,b=a.getContext("2d");b.save();b.fillStyle="#ffffff";b.fillRect(0,0,a.width,a.height);b.restore();for(a=0;a<this.D.length;++a)this.D[a].N();0<this.Oa&&this.Ge(b)}};this.$d=function(a){var b=!1;0<this.Ma&&(b=!0);this.Ma=this.qd;b?this.Ta=null:(this.Ta=a,this.de())};this.de=function(){this.Ma-=
this.pd/1E3;0>=this.Ma&&(this.Ma=0);this.N();var a=this;0<this.Ma&&setTimeout(function(){a.de()},this.pd)};this.Cb=function(a,b){this.width=a;this.height=b;this.canvas&&(this.canvas.width=a,this.canvas.height=b);this.ba.style.width=a+"px";this.ba.style.height=b+"px";this.N()};this.zf=function(a,b){this.ba.style.left=a+"px";this.ba.style.top=b+"px";this.ec&&(this.ec.style.left=a+this.ge.x+"px",this.ec.style.top=b+this.ge.y+"px")};this.Xd=function(){this.ba.style.display="none";this.ec&&(this.ec.style.display=
"none")};this.ke=function(){document.body.removeChild(this.ba);document.body.appendChild(this.ba)};this.oc=function(a){a.offsetX?(this.Xa=a.offsetX,this.Ya=a.offsetY):a.layerX&&(this.Xa=a.layerX,this.Ya=a.layerY)};this.ba.ondblclick=function(a){a.Ka=!0};this.Ge=function(a){a.strokeStyle="black";a.fillStyle="white";a.globalAlpha=.5;Va(a,this.width-this.Oa,this.height-this.Oa,1.5*this.Oa,1.5*this.Oa,4,!0,!0);a.globalAlpha=1};this.Gd=function(a,b){return a>=this.width-this.Oa&&b<=this.Oa};this.We=function(a,
b){return a>=this.width-this.Oa&&b>=this.height-this.Oa};this.ba.onmousedown=function(a){this.g.oc(a);for(var b=this.g.D.length-1;0<=b&&!a.Ka;--b)a.Ka=this.g.D[b].Qb(this.g.Xa-this.g.D[b].u.x,this.g.Ya-this.g.D[b].u.y);a.Ka||(this.g.Oc=a.pageX,this.g.Pc=a.pageY,this.g.zd=parseInt(this.g.ba.style.left),this.g.Ad=parseInt(this.g.ba.style.top),this.g.Be=parseInt(this.g.ba.style.width),this.g.Ae=parseInt(this.g.ba.style.height),S=this.g,Na=0,Oa=this.g.We(this.g.Xa,this.g.Ya)?"resize":this.g.Gd(this.g.Xa,
this.g.Ya)?"close":"move");return!1};this.ba.onwheel=function(a){for(var b=this.g.D.length-1;0<=b&&!a.Ka;--b)this.g.D[b].Xc&&(a.Ka=this.g.D[b].Xc(a));return!1};this.ba.onmouseup=function(a){this.g.oc(a);for(var b=this.g.D.length-1;0<=b&&!a.Ka;--b)a.Ka=this.g.D[b].Sb(this.g.Xa-this.g.D[b].u.x,this.g.Ya-this.g.D[b].u.y)};this.ba.onmousemove=function(a){this.g.oc(a);for(var b=this.g.D.length-1;0<=b&&!a.Ka;--b)a.Ka=this.g.D[b].Rb(this.g.Xa-this.g.D[b].u.x,this.g.Ya-this.g.D[b].u.y);return!1};this.Xd()}
document.onmouseup=function(a){S&&"close"==Oa&&(S.oc(a),S.Gd(S.Xa,S.Ya)&&S.Xd());S=null;return!0};document.onmousemove=function(a){var c=a.pageX;a=a.pageY;S&&(0==Na&&S.ke(),Na++,"move"==Oa?(c=S.zd+c-S.Oc,a=S.Ad+a-S.Pc,0>c&&(c=0),0>a&&(a=0),S.zf(c,a)):"resize"==Oa&&(c=S.Be+c-S.Oc,a=S.Ae+a-S.Pc,64>c&&(c=64),64>a&&(a=64),S.Cb(c,a)))};function Wa(a){var c=Xa;a=a*Math.PI/180;return new I(c.x+160*Math.sin(a),c.y+160*-Math.cos(a))}
function Ya(a,c){var d=document.createElement("div");d.id="stopwatchDiv";d.style.margin="0px auto";d.style.position="absolute";d.style.left=a;d.style.top=c;d.style.border="1px solid #999";d.style.Xf="0 0 30px 5px #999";d.style.cssText+="-moz-box-shadow: 0 0 30px 5px #999; -webkit-box-shadow: 0 0 30px 5px #999;";d.onselectstart=function(){return!1};d.onmousedown=function(){return!1};document.body.appendChild(d);return d}function Ea(){for(var a=0;a<Ma.length;++a)Ma[a].N()}
function Va(a,c,d,b,e,f,h,g){a.beginPath();a.moveTo(c,d+f);a.lineTo(c,d+e-f);a.quadraticCurveTo(c,d+e,c+f,d+e);a.lineTo(c+b-f,d+e);a.quadraticCurveTo(c+b,d+e,c+b,d+e-f);a.lineTo(c+b,d+f);a.quadraticCurveTo(c+b,d,c+b-f,d);a.lineTo(c+f,d);a.quadraticCurveTo(c,d,c,d+f);h&&a.stroke();g&&a.fill()}function Ja(a,c,d,b,e,f,h,g,l){a.fillStyle=h;a.textAlign=g;a.textBaseline=l;a.font=f+" "+e.toFixed(1)+"px Helvetica";a.fillText(c,d,b)}function Aa(){Ea()}var Za=Ma,T=new K(1,1,!1);
new function(a){this.valid=!1;this.H=1;this.a=a;a.ya.push(this);this.name=void 0;this.Va=!0;this.Td=function(){if(!this.valid&&(this.B=a.rf(this.H),0<=this.B)){for(var c=this.C=0;c<this.H;++c)this.C|=1<<c;this.oa=F(this.C,this.B);this.valid=!0}this.a.Cc()};this.release=function(){this.valid&&(this.valid=!1,this.a.qf(this.H))};this.ja=function(a){return this.valid?this.a.ja(a<<this.B):0};this.jf=function(a,d){if(this.valid){var b=a<<this.B,e=this.B,f=this.a.c-(this.B+this.H),h=0;for(below=0;below<
1<<e;++below)for(above=0;above<1<<f;++above){var g=this.a.ja(b|below|above<<this.B+this.H),l=g.x*g.x+g.y*g.y,h=h+l;d&&1E-6<l&&d.push(g)}return h}return 0};this.Ib=function(a,d,b,e,f){d&&d.da&&(e=d,d=null);var h=this.a.za;f&&(h?this.a.A.F("not",f,0,0):this.a.X(f));var g=A(0,this.a.c);b=null==b?this.C:this.C&b;if(d){var l=A(0,this.a.c),m=this.H;d&&d.H<m&&(m=d.H);for(var n=0;n<m;++n)b&1<<n&&(l.set(0),l.eb(n+this.B,1,1),g.set(0),d&&g.eb(n+d.B,1,1),g.v(e),g.v(f),h?this.a.A.F(a,l,g,0):"cnot"==a?this.a.G(l,
g):"crootnot"==a?this.a.jc(l,g):"crootnot_inv"==a&&this.a.Kc(l,g));l.bb()}else g.set(0),g.v(e),g.v(f),a=oa([this,b]),h?this.a.A.F("cnot",a,g,0):this.a.G(a,g),a.bb();g.bb();f&&(h?this.a.A.F("not",f,0,0):this.a.X(f))};this.X=function(a){this.Ib("cnot",null,a,null,null)};this.G=function(a,d,b,e){this.Ib("cnot",a,d,b,e)};this.jc=function(a,d,b,e){this.Ib("crootnot",a,d,b,e)};this.Kc=function(a,d,b,e){this.Ib("crootnot_inv",a,d,b,e)};this.Dd=function(a,d,b,e,f){e&&e.Va&&(e=e.oa);f&&f.Va&&(f=f.oa);f&&this.a.A.F("not",
f,0,0);null==b&&(b=this.C);var h=0;E(e)&&E(f)||(h?(h=A(e),h.v(f)):(h=A(f),h.v(e)));e=this.H;targetBits=A(0,this.a.c);if(null==d||d==this){targetBits.set(0);for(var g=0;g<e;++g)b&1<<g&&targetBits.R(g+this.B,1);this.a.A.F(a,targetBits,h,0)}else for(d.H<e&&(e=d.H),g=0;g<e;++g)b&1<<g&&(targetBits.set(0),targetBits.R(g+this.B,1),targetBits.R(g+d.B,1),this.a.A.F(a,targetBits,h,0));f&&this.a.A.F("not",f,0,0)};this.mc=function(a,d,b,e){this.Dd("exchange",a,d,b,e)};this.ed=function(a,d,b,e){this.Dd("rootexchange",
a,d,b,e)};this.Ca=function(a,d){var b=F(null==a?this.C:this.C&a,this.B);this.a.A.F("hadamard",b,d)};this.gc=function(a,d,b,e){e&&this.a.A.F("not",e,0,0);var f=A(0,this.a.c);d=null==d?this.C:this.C&d;if(a){var h=A(0,this.a.c),g=this.H;a&&a.H<g&&(g=a.H);for(var l=0;l<g;++l)d&1<<l&&(h.set(0),h.eb(l+this.B,1,1),f.set(0),a&&f.eb(l+a.B,1,1),f.v(b),f.v(e),this.a.A.F("chadamard",h,f,0))}else f.set(0),f.v(b),f.v(e),a=oa([this,d]),this.a.A.F("chadamard",a,f,0),a.bb();e&&this.a.A.F("not",e,0,0)};this.sd=function(a,
d){null==a&&(a=.5);var b=F(null==d?this.C:this.C&d,this.B);this.a.A.F("optical_beamsplitter",b,null,a)};this.Cd=function(a,d){null==a&&(a=.5);var b=F(null==d?this.C:this.C&d,this.B);this.a.A.F("dual_rail_beamsplitter",b,null,a)};this.Bc=function(a){var d=null==a?this.C:this.C&a,b=null;a&&a.Va?(b=F(1,this.B),b.R(a.B,1)):b=F(d,this.B);this.a.A.F("postselect_qubit_pair",b)};this.wc=function(a){if(a.Va)return this.Ib("pair_source",a,null,null,null);a=F(null==a?this.C:this.C&a,this.B);this.a.A.F("pair_source",
a,null,0)};this.Zc=function(a,d){null==d&&(d=0);var b=F(null==a?this.C:this.C&a,this.B);this.a.A.F("polarization_grating_in",b,null,d)};this.$c=function(a,d){null==d&&(d=0);var b=F(null==a?this.C:this.C&a,this.B);this.a.A.F("polarization_grating_out",b,null,d)};this.yc=this.sa=function(a,d,b,e){b&&b.Va&&(b=b.oa);e&&e.Va&&(e=e.oa);d=F(null==d?this.C:this.C&d,this.B);e&&this.a.A.F("not",e,0,0);d.v(b);d.v(e);this.a.A.F("phase",0,d,a);e&&this.a.A.F("not",e,0,0)};this.Yb=function(a,d,b){d&&d.Va&&(b=d.oa,
d=null);d=F(null==d?this.C:this.C&d,this.B);this.a.A.F("crotatex",d,b,a)};this.Ud=function(a,d,b){d&&d.Va&&(b=d.oa,d=null);d=F(null==d?this.C:this.C&d,this.B);this.a.A.F("crotatey",d,b,a)};this.rotate=this.Yb;this.read=function(a){var d=null==a?this.C:this.C&a;a=F(d,this.B);if(this.a.za){var b=this.a.A.F("read",a,0,0);b&&b.finish()}b=ea(this.a.read(a));d=b.Mb(this.B,d);a.bb();b.bb();return d};this.mb=function(a,d){var b=F(null==d?this.C:this.C&d,this.B);this.a.za?(b=this.a.A.F("postselect",b,a,0))&&
b.finish():this.a.mb(b,a)};this.je=function(a){return F(null==a?this.C:this.C&a,this.B)};this.write=function(a,d){var b=null==d?this.C:this.C&d;null==this.bc&&(this.bc=F(b,this.B));null==this.cc&&(this.cc=F(a,this.B));this.bc.set(0);this.bc.eb(this.B,b,b);this.cc.set(0);this.cc.eb(this.B,a,a);this.a.za?this.a.A.F("write",this.bc,this.cc,0):this.a.write(this.bc,this.cc)};this.add=function(a,d,b,e,f){var h=this.a.za;f||(f=0);if(a.toFixed)return this.ee(a<<f,d,b);b&&(h?this.a.A.F("not",b,0,0):this.a.X(b));
null==this.La&&(this.La=[]);null!=this.Gb&&0<this.Gb.length&&this.Gb[0].H<this.a.c&&(this.Gb=null);null==this.Gb&&(this.Gb=[]);var g=[];null==this.Z&&(this.Z=A(this.oa,this.a.c));null==this.fb&&(this.fb=A(this.Z));this.Z.set(this.oa);this.fb.set(this.oa);for(var l=0;l<f;++l)this.fb.ac();this.fb.la(this.Z);null==this.Ba&&(this.Ba=A(this.Z));null==this.ha&&(this.ha=A(this.Z));null==this.fa&&(this.fa=A(this.Z));null==this.qb&&(this.qb=A(0,this.a.c));this.qb.set(0);for(this.qb.R(a.B,1);this.qb.ib(a.oa);){this.ha.set(0);
this.ha.R(this.B+(this.H-1),1);this.Ba.set(this.Z);for(this.Ba.Eb();this.ha.ib(this.Z)&&this.ha.ib(this.fb);)this.fa.set(this.Ba),this.fa.la(this.Z),this.fa.la(this.fb),this.fa.v(d),this.fa.v(b),this.fa.v(this.qb),g.length==this.La.length?(f=new Ia("cnot",this.ha,this.fa,0,null),this.La.push(f)):(f=this.La[g.length],f.h.set(this.ha),f.o.set(this.fa)),g.push(f),this.Ba.Eb(),this.ha.Eb();this.qb.ac();this.Z.ac();this.Z.la(this.oa);this.fb.ac();this.fb.la(this.oa)}if(e)if(h)for(l=g.length-1;0<=l;--l)this.a.A.F(g[l]);
else for(l=g.length-1;0<=l;--l)this.a.G(g[l].h,g[l].o);else if(h)for(l=0;l<g.length;++l)this.a.A.F(g[l]);else for(l=0;l<g.length;++l)this.a.G(g[l].h,g[l].o);b&&(h?this.a.A.F("not",b,0,0):this.a.X(b))};this.ee=function(a,d,b){var e=this.a.za,f=!1;1<this.H&&a&1<<this.H-1&&(f=!0,a=-a&this.C);var h=[];null==this.La&&(this.La=[]);b&&(e?this.a.A.F("not",b,0,0):this.a.X(b));a|=0;for(var g=0;a&~g;)g=g<<1|1;g&=this.C;null==this.Z&&(this.Z=A(this.oa,this.a.c));null==this.Ba&&(this.Ba=A(this.Z));null==this.ha&&
(this.ha=A(this.Z));null==this.fa&&(this.fa=A(this.Z));this.Z.set(this.oa);for(var l=1;l&g;){this.ha.set(0);this.ha.R(this.B+(this.H-1),1);this.Ba.set(this.Z);for(this.Ba.Eb();this.ha.ib(this.Z);){if(a&l){this.fa.set(this.Ba);this.fa.la(this.Z);this.fa.v(d);this.fa.v(b);if(h.length==this.La.length){var m=new Ia("cnot",this.ha,this.fa,0,null);this.La.push(m)}else m=this.La[h.length],m.h.set(this.ha),m.o.set(this.fa);h.push(m)}this.Ba.Eb();this.ha.Eb()}l<<=1;this.Z.ac();this.Z.la(this.oa)}if(f)if(e)for(a=
h.length-1;0<=a;--a)this.a.A.F(h[a]);else for(a=h.length-1;0<=a;--a)this.a.G(h[a].h,h[a].o);else if(e)for(a=0;a<h.length;++a)this.a.A.F(h[a]);else for(a=0;a<h.length;++a)this.a.G(h[a].h,h[a].o);b&&(e?this.a.A.F("not",b,0,0):this.a.X(b))};this.Td()}(T);T.pb();ya(T,1);var $a=Ya(130,360),ab=document.createElement("canvas");$a.appendChild(ab);var U=new Ua(ab,$a);U.Cb(351,447);
var Xa=(new function(a,c){var d=new I(0,0);this.a=a;this.g=c;this.U=1;this.u=new I(d.x,d.y);this.scale=1;this.Mc=147;this.Nc=267;this.we=function(){return new I(this.Mc*this.scale,this.Nc*this.scale)};this.Lc=85;this.ob=[];this.ob.push(new Ba(184,291));this.ob.push(new Ba(105.5,265));this.Ue=new za("images/gold_watch_open8_301.png");this.Se=new za("images/gold_watch_closed_301.png");a.D.push(this);c.D.push(this);this.N=function(){var b=this.g.canvas.getContext("2d");b.save();var a=this.a.Ic(this.U),
c=this.Se;a&&(c=this.Ue);if(null!=c&&0<c.width){this.size=new I(c.width*this.scale,c.height*this.scale);try{b.drawImage(c,this.u.x,this.u.y,this.size.x,this.size.y)}catch(d){}if(a||this.a.fc){var c=this.u.x+this.scale*this.Mc,h=this.u.y+this.scale*this.Nc,g=this.scale*this.Lc,l=60;a?this.a.vd(this.U)&&(l-=90):l-=90*this.a.Pa(this.U);var m=l*Math.PI/180,l=Math.sin(m),m=Math.cos(m);b.save();b.beginPath();b.moveTo(c,h);b.lineTo(c+l*g,h-m*g);if(a)b.lineWidth=1,b.strokeStyle="#000000";else{b.globalAlpha=
.05;b.strokeStyle="#ffffff";b.lineCap="round";for(c=30;2<c;c-=2)b.lineWidth=c,b.stroke();b.globalAlpha=1;b.strokeStyle="#b8cce4";b.strokeStyle="#548dd4";b.lineWidth=2}b.stroke();b.restore();if(a)for(a=0;2>a;++a)g=20*this.scale,l=-30+360*this.ob[a].count/60,m=l*Math.PI/180,l=Math.sin(m),m=Math.cos(m),c=this.u.x+this.scale*this.ob[a].x,h=this.u.y+this.scale*this.ob[a].y,b.save(),b.beginPath(),b.lineTo(c-l*g*.5,h+m*g*.5),b.lineTo(c+l*g,h-m*g),b.lineWidth=1,b.strokeStyle="#000000",b.stroke(),b.restore()}}b.restore()};
this.K=function(){this.N()};this.message=function(b,a,c){0!=(a&this.U)&&"incrementResultDial"==b&&(c?this.ob[1].count++:this.ob[0].count++,this.N())};this.Qb=function(b,a){if(0<=b&&0<=a&&b<this.size.x&&a<this.size.y){var c=b-this.scale*this.Mc,d=a-this.scale*this.Nc;if(c*c+d*d<=this.scale*this.Lc*this.scale*this.Lc)return this.a.Ic(this.U)?this.a.ia(this.U):this.a.read(this.U),this.a.K(),!0}return!1};this.Sb=function(){};this.Rb=function(){}}(T,U)).we();Xa.x-=16;Xa.y-=16;var V=Wa(-2);
new function(a,c,d){var b=new Ca(a,c,d,"images/not_charm_35.png");b.U=1;b.label="not";b.sb=function(){b.a.A&&b.a.A.F("not",b.U,0,0)};return b}(T,U,V);V=Wa(17);new function(a,c,d){var b=new Ca(a,c,d,"images/cointoss_charm_35.png");b.U=1;b.label="random";b.sb=function(){var a=b.a.Ic(b.U);b.a.read(b.U);b.a.Ca(b.U);b.a.read(b.U);b.a.message("incrementResultDial",b.U,b.a.vd(b.U));a||b.a.ia(b.U);b.a.K()};return b}(T,U,V);V=Wa(36);
new function(a,c,d){var b=new Ca(a,c,d,"images/hadamard_charm_35.png");b.U=1;b.label="hadamard";b.sb=function(){b.a.Ca(b.U)};return b}(T,U,V);V=Wa(55);new function(a,c,d){var b=new Ca(a,c,d,"images/rotate_charm_35.png");b.U=1;b.label="rotate";b.sb=function(){b.a.rotate(b.U,20)};return b}(T,U,V);V=Wa(74);new function(a,c,d){var b=new Ca(a,c,d,"images/phase_charm_35.png");b.U=1;b.label="phase shift";b.sb=function(){b.a.sa(b.U,20)};return b}(T,U,V);V=Wa(93);
new function(a,c,d){this.a=a;this.g=c;this.scale=1;this.u=new I(d.x,d.y);this.Ve=new za("images/cat_in_box_35.png");this.Te=new za("images/opaque_box_35.png");a.D.push(this);c.D.push(this);this.N=function(){var b=this.g.canvas.getContext("2d");b.save();var a=this.Te;this.a.fc&&(a=this.Ve);if(null!=a&&0<a.width){this.size=new I(a.width*this.scale,a.height*this.scale);try{b.drawImage(a,this.u.x,this.u.y,this.size.x,this.size.y)}catch(c){}}b.restore()};this.K=function(){this.N()};this.message=function(){};
this.Qb=function(b,a){return 0<=b&&0<=a&&b<this.size.x&&a<this.size.y?(this.a.Jf(),!0):!1};this.Sb=function(){};this.Rb=function(){}}(T,U,V);Qa=U;Za.push(Qa);
Ta=function(a){this.a=a;this.ba=Ya(520,100);div.style.cssText+="background-color: #fff;";var c="",d="";a.Kb?d='checked="checked"':c='checked="checked"';var b;b='<font face="Tahoma, Digital, Arial, Helvetica, sans-serif" size="2"><table>  <tr>    <td><font size="4"><b>QC Engine Setup</b></font></td>';b+="  </tr><tr>";b+="    <td>";b+="      <table>";b+="        <tr>";b+="          <td>";b+="            Total Qubits ";b+='            <input type="text" id="numQubitsSet" size="4" value="'+a.c+'"/>';
b+='            <input type="button" onclick="qcEngineSetupPanel.incQubits(1, 1);" value="+" />';b+='            <input type="button" onclick="qcEngineSetupPanel.incQubits(-1, -1);" value="-" />';b+="          </td>";b+="        </tr><tr>";b+="          <td>";b+="            Block Count ";b+='            <input type="text" id="numBlockQubitsSet" size="4" value="'+a.uc+'"/>';b+='            <input type="button" onclick="qcEngineSetupPanel.incQubits(0, 1);" value="+" />';b+='            <input type="button" onclick="qcEngineSetupPanel.incQubits(0, -1);" value="-" />';
b+="          </td>";b+="        </tr><tr>";b+='          <td><input type="radio" id="singlePrecisionRadio" name="group1" onclick="qcEngineSetupPanel.checkQCSettings();" value="Single" '+c+">Single precision</input></td>";b+="        </tr><tr>";b+='          <td><input type="radio" id="doublePrecisionRadio" name="group1" onclick="qcEngineSetupPanel.checkQCSettings();" value="Double" '+d+">Double precision</input></td>";b+="        </tr><tr>";b+='          <td><input type="button" onclick="startQCSim();" value="Start QC Simulation" style="background-color:#8f8; color:#000;"/></td>';
b+="        </tr><tr>";b+="        </tr><tr>";b+='          <td><input type="button" onclick="stopQCSim();" value="Stop QC Simulation" style="background-color:#f88; color:#000;"/></td>';b+="        </tr><tr>";b+="        </tr>";b+="      </table>";b+="    </td>";b+='    <td valign="top">';b+='      <span id="setupNotesSpan"></span>';b+="    </td>";b+="  </tr>";b+="</table>";b+="</font>";this.ba.innerHTML=b;this.df=document.getElementById("setupNotesSpan");this.ef=document.getElementById("numQubitsSet");
this.ze=document.getElementById("doublePrecisionRadio");this.g=new Ua(null,this.ba);this.mf=function(b){this.df.innerHTML=b};this.lf=function(b){for(var a="",c=b;10<=c;)c-=10;c=1<<c;if(10>b)a+=c+" bytes";else if(20>b)a+=c+" KB";else if(30>b)a+=c+" MB";else if(40>b)a+=c+" GB";else if(50>b)a+=c+" TB";else{for(a=a+"about "+c;50<=b;b-=10)a+=",000";a+=" TB"}return a};this.Zd=function(a,b){var c;c=""+(a+" qubits, ");var d=3;b&&d++;return c=(b?c+"double precision<br/>":c+"single precision<br/>")+("Required data size: "+
(1<<d)+"*2<sup>"+a+"</sup> = "+this.lf(a+d))};this.pe=function(){var a;a="<b>Current QC Status: </b>";a=this.a.active?a+"Active and running, all systems go<br/>"+this.Zd(this.a.c,this.a.Kb):a+'Inactive. Press "Start QC Simulation" to activate.<br/>';var b=parseFloat(this.ef.value),c=!1;this.ze.checked&&(c=!0);a+="<hr/><b>Requested QC Status: </b>";a+=this.Zd(b,c);this.mf(a)};this.pe();return this.g}(T);Za.push(Ta);var bb=Ya(600,470),cb=document.createElement("canvas");bb.appendChild(cb);
var db=new Ua(cb,bb);db.Cb(500,150);
new function(a,c){var d=new I(0,0);null==Fa&&(Fa=new za("images/rotate_charm_35.png"));this.a=a;this.Ra=c;a.A=this;c.A=this;this.$=this.Gc=this.scale=1;this.Jd=20;this.Wc=50;this.f=20;this.Ac=!1;this.wd=!0;this.zc=1;this.xb=0;this.Ia=null;this.ub=-1;this.ye=!0;this.Bd=!1;this.lc=.2;this.u=new I(d.x,d.y);this.size=new I(this.Ra.canvas.width,this.Ra.canvas.height);this.ca=0;this.s=[];this.s.push(new Ia("cnot",1,0,0,this.Ia));this.s.push(new Ia("rotate",1,2,0,this.Ia));this.s.push(new Ia("phaseshift",
1,4,0,this.Ia));Ga=Ha=this.nd=!0;a.D.push(this);c.D.push(this);this.ne=function(){this.scale=this.Gc;this.scale*=this.$};this.De=function(a){var c=this.xb=0,d=0;this.Wa=a.canvas.height/(this.f*this.$);this.Wa>this.a.c&&(this.Wa=this.a.c);for(var h=0;h<this.Wa;++h){var g=this.a.pc(h),l="0x"+this.a.Sc(h),m=1.75*u,n=0;Ja(a,"",m,n,14,"bold","#000","left","middle");c=Math.max(c,a.measureText(g).width);d=Math.max(d,a.measureText(l).width)}this.xb=10+c+d;a.save();c=null;for(h=0;h<this.Wa;++h){var u=.4*this.f;
a.lineWidth=1;m=1.75*u+this.xb;n=0;Ja(a,"0x"+this.a.Sc(h),m,n,14,"bold","#000","right","middle");g=this.a.pc(h);if(g!=c){c=g;l=0;for(m=h+1;m<this.Wa&&this.a.pc(m)==g;m++)l++;m=1.75*u+this.xb-(10+d);n=l/2*this.f;"(util)"!=g&&Ja(a,g,m,n,14,"bold","#000","right","middle");a.save();a.strokeStyle="rgba(0, 100, 125, 1.0)";a.lineWidth=1;g=a;m+=5;u=-.5*this.f;l=this.f*(l+1);n=.5*this.f;g.beginPath();g.moveTo(m+n,u);g.quadraticCurveTo(m,u,m,u+n);g.lineTo(m,u+n);g.lineTo(m,u+l-n);g.quadraticCurveTo(m,u+l,m+
n,u+l);g.stroke();a.restore()}a.translate(0,this.f)}a.restore()};this.clear=function(){this.Jc();this.Bd=!1;for(var a=this.ca=0;a<this.s.length;++a){var c=this.s[a];this.s[a]=null;delete c}this.s=[]};this.sf=function(){this.a.Aa=!1;this.I&&(this.I.active=!1);for(var a=this.ca=0;a<this.s.length;++a){var c=this.s[a];c.nb=null;c.bd=null}this.a.Fa();this.a.Ea(0,1,0);Ra.$d(null)};this.cd=function(a){this.Jc();this.s.splice(a,1);this.ca>=a&&this.ca--};this.F=function(a,c,d,h){1E6<this.s.length&&(this.clear(),
this.xe());var g=a,g=null!=a.b?new Ia(g.b,g.h,g.o,g.T,this.Ia,void 0):new Ia(a,c,d,h,this.Ia,void 0);if(!this.nd)return g.Qc(this.a,1),null;this.s.splice(this.ca,0,g);this.ye&&this.advance(1);return g};this.xe=function(){this.nd=!1};this.advance=function(a){if(this.nd){if(0>a&&!L.Nf){var c=!1;if(-1==a&&!this.Vf&&0<this.ca){var d=this.s[this.ca-1];if("not"==d.b||"cnot"==d.b)c=!0}if(!c){a=this.ca+a;this.sf();0>a&&(a=0);this.advance(a);return}}c=1;0>a&&(c=-1,a=-a);d=this.s.length;this.W&&(d=this.W.length);
var h=null,g=this.a.za;this.a.za=!1;for(var l=0;l<a;++l){l==a-1&&(this.a.za=g);if(0==this.ca&&0>c||this.ca==d&&0<c)return;var m=this.ca;0>c?(m=this.ca-1,this.ca--):this.ca++;if(this.W)for(var n=0;n<this.W[m].length;++n)h=this.W[m][n],h.Qc(this.a,c);else h=this.s[m],h.Qc(this.a,c)}this.a.za=g;this.a.za&&Ra.$d(h)}};this.Fe=function(a){var c=this.f*this.zc,d=this.f;a.save();for(var h=-1,g=0,l=0;l<this.s.length;++l){var m=this.s[l].Ia,n=null;l<this.s.length-1&&(n=this.s[l+1].Ia);if(n==m)g++;else{if(m){var u=
.1*c,k=h,v=g;if(this.W)for(k=1E6,v=-1;h<=g;++h)0<=h&&null!=this.s[h].Da&&(k=Math.min(k,this.s[h].Da),v=Math.max(v,this.s[h].Da),0==k&&(k=-1));var n=c*k+u+.5*c,h=-1.3*d,k=c*(v-k)-2*u,u=(this.a.c+1.3)*d,v=.5*this.f,r=!0;this.Ac&&(r=!1);a.save();a.strokeStyle="rgba(0, 100, 125, 1.0)";a.fillStyle="rgba(0, 0, 0, 0.05)";Va(a,n,h,k,u,v,!1,r);var r=a,p=n,t=h,w=k,x=u;r.beginPath();r.moveTo(p,t+v);r.moveTo(p,t+x-v);r.quadraticCurveTo(p,t+x,p+v,t+x);r.lineTo(p+w-v,t+x);r.quadraticCurveTo(p+w,t+x,p+w,t+x-v);
r.moveTo(p+w,t+v);r.quadraticCurveTo(p+w,t,p+w-v,t);r.lineTo(p+v,t);r.quadraticCurveTo(p,t,p,t+v);r.stroke();a.fillStyle="rgba(0, 100, 125, 1.0)";n+=.5*k;u=h+u+3;Ja(a,m,n,h-2,12,"","rgba(0, 100, 125, 1.0)","center","bottom");Ja(a,m,n,u,12,"","rgba(0, 100, 125, 1.0)","center","top");a.restore()}h=g;g++;if(h*this.$>a.canvas.width)break}}a.restore()};this.Je=function(a,c){a.save();for(var d=this.f*this.zc,h=0;h<this.s.length;++h)if(!c||!(h<c[0]||h>c[1])){a.save();var g=this.s[h],l=d*h,m=h;null!=g.Da&&
(l=d*g.Da,l+=4*g.Ub,m=g.Da);if(l*this.$>a.canvas.width+this.f){a.restore();break}a.translate(l,0);for(var n=.4*this.f,u=1E3,k=-1E3,v=0;v<this.Wa;++v)if(g.h.O(v)||g.o.O(v))u>v&&(u=v),k<v&&(k=v);if(!g.o.Uc()||"exchange"==g.b||"rootexchange"==g.b||"rootexchange_inv"==g.b||"dual_rail_beamsplitter"==g.b||"postselect_qubit_pair"==g.b||"pair_source"==g.b||"polarization_grating_in"==g.b||"polarization_grating_out"==g.b){v=!1;"phase"==g.b&&0==g.T&&(v=!0);v&&(a.globalAlpha=.25);if(u<k)if("dual_rail_beamsplitter"==
g.b||"postselect_qubit_pair"==g.b||"polarization_grating_in"==g.b||"polarization_grating_out"==g.b)u+1<k&&(a.lineWidth=.5,a.beginPath(),a.moveTo(0,this.f*(u+.25)),a.lineTo(0,this.f*(k-.25)),a.stroke());else{if("pair_source"==g.b){var r=.08*this.f;a.lineWidth=1;a.strokeStyle="#08f";a.beginPath();a.moveTo(-r,this.f*u);a.lineTo(-r,this.f*k);a.stroke();a.strokeStyle="#f20";a.beginPath();a.moveTo(r,this.f*u);a.lineTo(r,this.f*k)}else a.lineWidth=2,a.beginPath(),a.moveTo(0,this.f*u),a.lineTo(0,this.f*k);
a.stroke()}v&&(a.globalAlpha=1)}if("optical_beamsplitter"==g.b||"coptical_beamsplitter"==g.b||"dual_rail_beamsplitter"==g.b||"optical_phase"==g.b||"phase"==g.b||"rotatex"==g.b||"rotatey"==g.b||"crotatex"==g.b||"crotatey"==g.b)a.save(),a.font="bold 11px sans-serif",a.textAlign="center",a.textBaseline="middle",u=0,k=1*-this.f,v="","optical_beamsplitter"==g.b||"coptical_beamsplitter"==g.b||"dual_rail_beamsplitter"==g.b||"pair_source"==g.b?(r=g.T.toFixed(1),100*g.T%10&&(a.font="bold 8px sans-serif",a.textBaseline=
"middle",r=g.T.toFixed(2)),.5!=r&&(v+=r)):(r=!1,"phase"==g.b&&1<g.o.Jb()&&180==g.T&&(r=!0),r||(r=g.T.toFixed(0),10*g.T%10&&(a.font="bold 8px sans-serif",a.textBaseline="middle",r=g.T.toFixed(1)),v+=r,v+="\u00b0")),a.fillText(v,u,k),a.restore();for(v=0;v<this.Wa;++v)if(g.h.O(v))g.N(a,0,this.f*v,n,v,this,l,m);else if(g.Ha&&g.Ha.O(v)&&"dual_rail_beamsplitter"==g.b){var u=0,k=this.f*v,r=.25*this.f,p=g.h.V()<v?1:-1;a.strokeStyle="white";a.lineWidth=2;a.beginPath();a.moveTo(u-r,k);a.lineTo(u+r,k);a.stroke();
a.strokeStyle="black";a.lineWidth=2;a.beginPath();a.moveTo(u-r,k);a.lineTo(u-.5*r,k+.5*p*r);a.lineTo(u+.5*r,k+.5*p*r);a.lineTo(u+r,k);a.stroke();a.lineWidth=1;a.beginPath();a.moveTo(u-3*r,k+1.75*p*r);a.lineTo(u-r,k+1.75*p*r);a.lineTo(u-.5*r,k+1.25*p*r);a.lineTo(u+.5*r,k+1.25*p*r);a.lineTo(u+r,k+1.75*p*r);a.lineTo(u+3*r,k+1.75*p*r);a.stroke()}else g.o.O(v)&&("phase"==g.b||"optical_phase"==g.b?(a.lineWidth=1,a.strokeStyle="black",u=!1,(0==g.T||180==g.T)&&1<g.o.Jb()&&(u=!0),0==g.T&&(a.globalAlpha=.25),
u?(a.fillStyle="black",Q(a,0,this.f*v,.2*this.f)):(a.fillStyle="white",R(a,0,this.f*v,.4*this.f),Q(a,0,this.f*v,.4*this.f),R(a,0,this.f*v,.15*this.f),a.beginPath(),a.lineTo(.03*this.f,this.f*v-.3*this.f),a.lineTo(.03*-this.f,this.f*v+.3*this.f),a.stroke()),0==g.T&&(a.globalAlpha=1),0<g.xa&&L.Oe&&(n=.4*this.f,u=g.xa/L.Nd,k=a.createRadialGradient(0,this.f*v,0,0,this.f*v,2.25*n),k.addColorStop(0,"rgba(255,100,0,255)"),k.addColorStop(1,"rgba(255,0,0,0"),a.globalAlpha=u,a.fillStyle=k,Q(a,0,this.f*v,2.25*
n),a.fillStyle="#fff",a.globalAlpha=1)):"pair_source"==g.b?(u=g.o.V(),k=g.o.P(),a.fillStyle="#08f",u==k?Q(a,0,this.f*v,.3*this.f):v==k?Q(a,0,this.f*v,.3*this.f,0,180):v==u&&Q(a,0,this.f*v,.3*this.f,180,0)):(a.fillStyle="black",Q(a,0,this.f*v,.2*this.f)));g.Ee(a,this.f*this.a.c,n);a.restore()}a.restore()};this.Ie=function(a){if(!(0>this.ub)){a.save();a.strokeStyle="orange";a.lineWidth=1;a.beginPath();var c=this.f*(this.ca-.5);a.lineTo(c,-this.f);a.lineTo(c,this.f*this.a.c);a.stroke();a.restore()}};
this.He=function(a){a.save();a.strokeStyle=this.Ac?"black":"gray";a.lineWidth=1;a.beginPath();var c=this.f*(this.ub-.5);a.lineTo(c,-this.f);a.lineTo(c,this.f*this.a.c);a.stroke();a.restore()};this.Ce=function(a){a.fillRect(0,0,this.Ra.canvas.width,this.Ra.canvas.height)};this.Ke=function(a){this.Ze();var c=this.f*this.zc,d=this.f;a.save();a.lineWidth=1;for(var h=0;h<this.Wa;++h){for(var g=a.strokeStyle="#dddddd",l="#dddddd",m=0,n=-1*c,u=0*c,k=1;k<this.Ga.length;++k)if(n=(k-1)*c,u=(k+0)*c,l=this.Ga[k].O(h)?
"#000000":"#dddddd",g!=l||k==this.Ga.length-1)a.strokeStyle=g,a.beginPath(),a.moveTo(m,0),k==this.Ga.length-1?a.lineTo(u,0):a.lineTo(n,0),a.stroke(),m=n,g=l;a.translate(0,d)}a.restore()};this.N=function(a,c){this.ne();c&&(0>c[0]&&(c[0]=c[1]),0>c[1]&&(c[1]=c[0]),c[1]<c[0]&&(c[1]=c[0]),c[0]--,c[1]++);var d=this.Ra.canvas.getContext("2d");d.save();d.fillStyle=this.Ac&&!this.wd?"#999":"#fff";this.Ce(d);d.scale(this.scale,this.scale);d.translate(this.Jd,this.Wc);this.De(d);d.translate(1.25*this.f+this.xb,
0);this.wd&&(this.Ke(d),this.Je(d,c));this.Ac&&(d.save(),d.translate(1,1),d.strokeStyle="black",d.lineWidth=8,d.globalAlpha=.1,eb(this,d),d.lineWidth=6,d.globalAlpha=.2,eb(this,d),d.lineWidth=4,d.globalAlpha=.4,eb(this,d),d.restore(),d.strokeStyle="white",d.lineWidth=2,d.globalAlpha=1,eb(this,d));0<=this.ub&&this.He(d);a||this.Ie(d);this.Fe(d);this.a.Ld&&this.a.Ld.Pf(d);d.restore()};this.K=function(){};this.message=function(){};this.Rc=function(a,c){a/=this.scale;c/=this.scale;var d=this.Jd+1.25*
this.f+this.xb,h=this.Wc-.5*this.f,g=this.Wc+this.f*this.a.c;numSlots=this.s.length;this.W&&(numSlots=this.W.length);return c>=h&&c<=g&&(d=1+Math.floor((a-d)/this.f),0<=d&&d<=numSlots)?d:-1};this.ud=function(){if(this.Nb){var a=this.xd-NaN,c=this.yd-NaN;1E4<a*a+c*c&&(this.Nb=!1)}};this.Xc=function(a){1==a.ctrlKey&&(a=a.deltaY,0<a&&(this.$*=.9),0>a&&(this.$*=1.1),.1>this.$&&(this.$=.1),3<this.$&&(this.$=3),this.N());return!1};this.Qb=function(a,c){return a>this.Ra.width-20&&c>this.Ra.height-20?!1:
0<=this.Rc(a,c)?(this.Nb=!0,this.xd=a,this.yd=c,!0):!1};this.Sb=function(a,c){this.ud();if(this.Nb){a=this.xd;c=this.yd;var d=this.Rc(a,c);0<=d&&this.ca!=d&&(this.advance(d-this.ca),this.a.Aa&&this.a.ka.ce(),this.a.I&&this.a.I.active&&this.a.I.be(),this.N(!1))}this.Nb=!1};this.Rb=function(a,c){if(a>this.Ra.width-20&&c>this.Ra.height-20)return!1;if(this.Nb)this.ud();else{var d=this.ub;this.ub=this.Rc(a,c);d!=this.ub&&this.N(!1)}};this.Ze=function(){var a=this.s.length+1;this.W&&(a=this.W.length+1);
this.Ga=Array(a);for(var c=0;c<a;++c)this.Ga[c]=new C(0,this.a.J.H);for(var d=new C(0,this.a.J.H),h=0;h<this.s.length;++h){var g=this.s[h],c=null==g.Da?h:g.Da;this.Ga[c].set(d);if("read"==g.b||"postselect"==g.b||"discard"==g.b)g.h.Hd(),d.la(g.h),g.h.Hd();else if("exchange"==g.b){var c=g.h.V(),l=d.O(c),m=g.h.P();d.R(c,d.O(m));d.R(m,l)}else"polarization_grating_out"==g.b?(c=g.h.V(),m=g.h.P(),0>g.T?d.R(m,0):d.R(c,0)):"nop"!=g.b&&"peek"!=g.b&&"not"!=g.b&&"cnot"!=g.b&&"start_photon_sim"!=g.b&&"stop_photon_sim"!=
g.b&&"start_chp_sim"!=g.b&&"stop_chp_sim"!=g.b&&("pair_source"==g.b&&d.v(g.o),d.v(g.h))}this.Ga[a-1].set(d)};this.oe=function(){var a=null!=this.W;this.Jc();for(var c=new C(this.a.c),d=0;d<this.s.length-1;++d){var h=this.s[d];if("not"==h.b||"cnot"==h.b||"hadamard"==h.b||"chadamard"==h.b||"exchange"==h.b||"cexchange"==h.b||"dual_rail_beamsplitter"==h.b||"pair_source"==h.b)for(var g="exchange"==h.b||"cexchange"==h.b||"dual_rail_beamsplitter"==h.b||"pair_source"==h.b,l=d+1;l<this.s.length;++l){var m=
!1,n=this.s[l];h.b==n.b?ja(h.o,n.o)?ja(h.h,n.h)?(this.cd(l),this.cd(d),d--,m=!0):g?(c.set(h.h),c.la(n.h),E(c)||(m=!0)):(h.h.od(n.h),this.cd(l)):(c.set(h.h),c.la(n.h),E(c)||(m=!0),c.set(h.h),c.la(n.o),E(c)||(m=!0),c.set(h.o),c.la(n.h),E(c)||(m=!0)):m=!0;if(m)break}}a&&this.gf(this.hf)};this.Jc=function(){this.ca=0;this.W=null;for(var a=0;a<this.s.length;++a){var c=this.s[a];c.Da=null;c.xc=null;c.Ub=null}};this.gf=function(a){this.ca=0;this.hf=a;this.oe();this.W=[];for(var c=new C(0,this.a.c),d=new C(0,
this.a.c),h=new C(0,this.a.c),g=0;g<this.s.length;++g){var l=0,m=this.s[g];c.set(m.h);c.v(m.o);c.v(m.Ha);d.set(0);for(var n=c.P(),u=c.V(),k=this.W.length-1;0<=k&&0==l;--k){for(var v=this.W[k],r=!0,p=0;p<v.length;++p)d.v(v[p].h),d.v(v[p].o),d.v(v[p].Ha),m.Ia!=v[p].Ia&&(r=!1);d.la(c);v=!E(d);r||a||(v=!0);v&&(l=k+1)}l>=this.W.length&&this.W.push([]);m.Da=l;m.xc=this.W[l].length;m.Ub=m.xc;0<m.xc&&(k=this.W[l][m.xc-1],h.set(k.h),h.v(k.o),h.v(k.Ha),r=h.P(),v=h.V(),m.Ub=-1==n||-1==r||u<r||n>v?k.Ub:1+k.Ub);
this.W[l].push(m)}console.log("parallelize: "+this.s.length+" -> "+this.W.length)}}(T,db);Sa=db;Za.push(Sa);var fb=Ya(580,270),gb=document.createElement("canvas"),hb=document.createElement("select"),W=document.createElement("div");fb.appendChild(gb);W.appendChild(hb);W.style.width="20px";W.style.height="40px";W.style.position="relative";W.style.zIndex=1;W.style.left=30;W.style.top=30;W.style.display="none";document.body.appendChild(W);var ib=new Ua(gb,fb);ib.Cb(500,200);ib.rc=hb;new Da(T,ib);Ra=ib;
Za.push(Ra);qReg.K();var jb;a:{for(var kb=document.cookie.split(";"),lb=0;lb<kb.length;lb++){for(var mb=kb[lb];" "==mb.charAt(0);)mb=mb.substring(1,mb.length);if(0==mb.indexOf("machineLevel_user=")){jb=mb.substring(18,mb.length);break a}}jb=null}
if(""!=jb&&null!=jb){gUserName=jb;gNeedImageRefresh=gNeedModelRefresh=!0;var nb=gUserName,ob=new Date;ob.setTime(ob.getTime()+432E8);document.cookie="machineLevel_user="+nb+("; expires="+ob.toGMTString())+"; path=/";var pb=gUserName;0==gUserName.indexOf("guest_")?(pb="Special Guest #"+gUserName.slice(6),Ka("signOutDiv",!1),Ka("suggestLogin",!0)):(Ka("suggestLogin",!1),Ka("signOutDiv",!0));gUserNameInput.value=pb};function qb(a){return null!=a.Xb?a.Xb:a}function rb(a){return null!=a.Xb?a.Fd:0}function sb(a,c){if(a.Xb)return a;null==c&&(c=0);return{Xb:a,Fd:c}}function tb(a,c){return sb(qb(a)+qb(c),rb(a)+rb(c))}function X(a,c){var d=qb(a),b=rb(a),e=qb(c),f=rb(c);return sb(d*e-b*f,d*f+b*e)}function ub(a){return"("+qb(a)+"+i"+rb(a)+")"}function vb(a){for(var c="",d=0;d<a.length;++d)var b=a[d],c=c+(b?b:"-");return c}
function wb(a,c,d){var b=[1,1,2,6,24,120,720,5040,40320,362880,3628800,39916800];this.Yd=a;this.ga=[];this.Pb=0;this.kb=new C(a.a.c);this.kb.set(0);this.Tb=1;this.Wb=[];for(a=0;a<d.length;++a){var e=d[a];e&&(this.Pb|=1<<a,this.kb.R(a,1));this.ga.push(e);this.Tb*=b[e];for(var f=0;f<e;++f)this.Wb.push(a)}this.fd=c;this.matches=function(a){if(a.length!=this.ga.length)return!1;for(var b=0;b<a.length;++b)if(a[b]!=this.ga[b])return!1;return!0};this.fe=function(){return sb(this.Yd.w[2*this.fd],this.Yd.w[2*
this.fd+1])};this.lb=function(){for(var a=vb(this.ga),a=a+"/",b=0;b<this.Wb.length;++b)a+=this.Wb[b];return a};this.print=function(a){var b="";a&&(b+=a);b+=" state "+this.fd+": "+this.lb()+" "+ub(this.fe());console.log(b)}}
function ma(){this.reset=function(a,c,d){this.ua=!1;this.bf=[];for(c=0;c<a.c;++c){var b=a.pc(c),e=a.Sc(c),f="("+b;if(""==b||"1"!=e)f+=":"+e;f+=")";this.bf.push(f)}this.a=a;new C(a.c);this.ue();if(0==this.Ja)console.log("There are no photons.");else{this.S=[];c=Array(this.a.c);f=[];b=[];for(e=0;e<this.a.$a;++e)if(f=this.a.ja(e),f.x||f.y){for(var h=0;h<this.a.c;++h)c[h]=e>>h&1;var f=this.S.length,g=this.Fc(c);this.S.length!=f&&b.push(g);g=!1;for(inst_index=0;inst_index<a.A.s.length;++inst_index){var l=
a.A.s[inst_index];l==d?g=!0:"stop_photon_sim"==l.b&&(g=!1);if(g&&("dual_rail_beamsplitter"==l.b||"exchange"==l.b))for(var f=b,b=[],m=l.h.P(),n=l.h.V(),u=0;u<f.length;++u){for(var k=f[u],h=0;h<this.a.c;++h)c[h]=k.ga[h];h=c[m];k=c[n];if("exchange"==l.b){c[m]=k;c[n]=h;for(var v=this.Fc(c),r=!1,p=0;p<b.length&&!r;++p)b[p]==v&&(r=!0);r||b.push(v)}else if("dual_rail_beamsplitter"==l.b)for(p=0;p<=h+k;++p){c[m]=p;c[n]=h+k-p;for(var v=this.Fc(c),r=!1,t=0;t<b.length&&!r;++t)b[t]==v&&(r=!0);r||b.push(v)}}}}this.ra=
this.S.length;this.ua&&console.log("States required: "+this.ra);d=8;a.Kb&&(d=8);this.Yc=2*this.ra;this.vc=this.Yc*d;4==d?(this.w=new Float32Array(new ArrayBuffer(this.vc)),this.gb=new Float32Array(new ArrayBuffer(this.vc))):(this.w=new Float64Array(new ArrayBuffer(this.vc)),this.gb=new Float64Array(new ArrayBuffer(this.vc)))}};this.Fc=function(a){for(var c=0;c<this.S.length;++c)if(this.S[c].matches(a))return console.log("addifnew OLD"+vb(a)),this.S[c];c=new wb(this,this.S.length,a);this.S.push(c);
console.log("addifnew    "+vb(a));return c};this.Qa=function(a){var c="";a&&(c+=a);console.log(c+"photonic sim state: \n");if(this.S&&this.S.length)for(a=0;a<this.S.length;++a)this.S[a].print();else console.log("There are no photons.")};this.ue=function(){for(var a=this.Ja=0;a<this.a.$a;++a){var c=this.a.ja(a);if(c.x||c.y){for(var c=0,d=a;d;)c+=d&1,d>>=1;this.Ja<c&&(this.Ja=c)}}console.log("Number of logical photons: "+this.Ja)};this.Lf=function(){for(var a=0;a<this.Yc;++a)this.w[a]=0;for(a=0;a<this.a.$a;++a){var c=
this.a.ja(a);if(c.x||c.y)for(var d=0;d<this.ra;++d)if(this.S[d].Pb==a){this.w[2*d]=c.x;this.w[2*d+1]=c.y;break}}this.Qa("Imported from logical")};this.ce=function(){this.a.Fa();for(var a=0,c=0;c<this.ra;++c){var d=this.S[c],b=this.w[2*c],e=this.w[2*c+1];if(b||e){var f=this.a.ja(d.Pb);f.x+=b;f.y+=e;this.a.Ea(d.Pb,f.x,f.y);a++}}0==a&&(console.log("Photon state ended empty. Likely error."),this.a.Ea(0,1,0));xa(this.a);this.a.K()};this.nf=function(a){for(var c="unitary: [[",d=0;d<a.length;++d){for(var c=
c+"[",b=0;b<a[d].length;++b)c+=ub(a[d][b]),b<a[d].length-1&&(c+=", ");c+="]"}console.log(c+"]")};this.Tb=function(a){for(var c=!1,d=1,b=0;!c;++b)for(var c=!0,e=0,f=0;f<a.length;++f)a[f]==b?(e++,d*=e):a[f]>b&&(c=!1);return d};this.Qd=function(a){null==this.Vb&&(this.Vb=[1]);for(;this.Vb.length<a.length;){for(var c=this.Vb.length,d=Array(c),b=0;b<c;++b)d[b]=Array(c);this.Vb.push(d)}if(1==a.length)return a[0][0];if(2==a.length)return tb(X(a[0][0],a[1][1]),X(a[0][1],a[1][0]));if(3==a.length)return c=
tb(0,X(a[0][0],X(a[1][2],a[2][1]))),c=tb(c,X(a[0][0],X(a[1][1],a[2][2]))),c=tb(c,X(a[0][1],X(a[1][0],a[2][2]))),c=tb(c,X(a[0][1],X(a[1][2],a[2][0]))),c=tb(c,X(a[0][2],X(a[1][0],a[2][1]))),c=tb(c,X(a[0][2],X(a[1][1],a[2][0])));for(var c=0,d=this.Vb[a.length-1],e=0;e<a.length;++e){for(b=0;b<a.length-1;++b)for(var f=0,h=0;h<a.length-1;++h)f==e&&f++,d[b][h]=a[b+1][f++];c=tb(c,X(a[0][e],this.Qd(d)))}return c};this.sd=function(a,c){null==c&&(c=.5);var d=Math.sqrt(c),b=Math.sqrt(1-c),e=ha(a),f=ia(a);if(0==
this.Ja)console.log("There are no photons.");else{for(var h=Array(this.Ja),g=0;g<this.Ja;++g)h[g]=Array(this.Ja);for(var l=Array(this.a.c),g=0;g<this.a.c;++g){l[g]=Array(this.a.c);for(var m=0;m<this.a.c;++m)l[g][m]=g==m?1:0}l[e][e]=l[f][f]=sb(d,0);l[f][e]=l[e][f]=sb(0,b);this.ua&&this.nf(l);for(g=0;g<this.Yc;++g)this.gb[g]=0;for(d=0;d<this.ra;++d)if(b=this.S[d],this.ua&&b.print("from: "),e=this.w[2*d],f=this.w[2*d+1],e||f){e={Xb:e,Fd:f};for(f=0;f<this.ra;++f){g=this.S[f];this.ua&&console.log("");
this.ua&&g.print("  to: ");for(m=0;m<this.Ja;++m)for(var n=0;n<this.Ja;++n)h[m][n]=l[g.Wb[m]][b.Wb[n]];var m=b.Tb,n=g.Tb,u=0,u=this.Qd(h),k=X(X(e,u),1/Math.sqrt(m*n));this.ua&&console.log("contrib to "+g.lb()+" from "+b.lb()+" is "+ub(k)+" perm: "+ub(u)+" n0: "+m+" n1: "+n);this.gb[2*f]+=qb(k);this.gb[2*f+1]+=rb(k)}this.ua&&console.log("")}h=this.w;this.w=this.gb;this.gb=h;this.Qa("-> beamsplitter result ")}};this.ie=function(a,c){null==c&&(c=.5);for(var d=Math.sqrt(c),b=0;b<this.ra;++b)if(this.S[b].kb.ib(a)){var e=
this.w[2*b+1];this.w[2*b]*=d;this.w[2*b+1]=d*e}this.Qa("-> beamsplitter_aux result ")};this.mb=function(a,c){for(var d=0;d<this.ra;++d)(c?!0:!1)!=this.S[d].kb.ib(a)&&(this.w[2*d]=0,this.w[2*d+1]=0);this.Qa("-> postselect result ")};this.Bc=function(a){var c=ha(a);a=ia(a);for(var d=0;d<this.ra;++d){var b=this.S[d];b.kb.O(c)==b.kb.O(a)&&(this.w[2*d]=0,this.w[2*d+1]=0)}this.Qa("-> postselect_qubit_pair result ")};this.mc=function(a){console.log(this.w);var c=ha(a);a=ia(a);for(var d=0;d<this.ra;++d)for(var b=
this.S[d],e=d+1;e<this.ra;++e){var f=this.S[e],h=!1;if(b.ga[c]==f.ga[a]&&b.ga[a]==f.ga[c])for(var h=!0,g=0;g<this.a.c&&h;++g)g!=c&&g!=a&&b.ga[g]!=f.ga[g]&&(h=!1);if(h){console.log("  swap buddies "+b.lb()+" <-> "+f.lb());b=this.w[2*d];f=this.w[2*d+1];this.w[2*d]=this.w[2*e];this.w[2*d+1]=this.w[2*e+1];this.w[2*e]=b;this.w[2*e+1]=f;break}}this.Qa("-> exchange result ");console.log(this.w)};this.wc=function(a){console.log(this.w);var c=ha(a);a=ia(a);for(var d=0;d<this.ra;++d)for(var b=this.S[d],e=d+
1;e<this.ra;++e){var f=this.S[e],h=!1;if(2==b.ga[c]&&0==b.ga[a]&&1==b.ga[c]&&1==b.ga[a])for(var h=!0,g=0;g<this.a.c&&h;++g)g!=c&&g!=a&&b.ga[g]!=f.ga[g]&&(h=!1);if(h){console.log("  pair_source buddies "+b.lb()+" <-> "+f.lb());b=this.w[2*d];f=this.w[2*d+1];this.w[2*d]=0;this.w[2*d+1]=0;this.w[2*e]=b;this.w[2*e+1]=f;break}}this.Qa("-> pair_source result ");console.log(this.w)};this.yc=function(a,c){console.log(this.w);for(var d=Math.PI*c/180,b=Math.sin(d),d=Math.cos(d),e=0;e<this.ra;++e)if(this.S[e].kb.ib(a)){var f=
this.w[2*e],h=this.w[2*e+1];this.w[2*e]=d*f+b*h;this.w[2*e+1]=d*h-b*f}this.Qa("-> phase shift result ")}}function Y(a,c,d,b,e){var f=a+.4*(c-a),h=a+.6*(c-a),g=.5*(a+f),l=.5*(c+h),m=.5*(d+b);e.moveTo(a,d);e.quadraticCurveTo(g,d,g,m);e.quadraticCurveTo(g,b,f,b);e.lineTo(h,b);e.quadraticCurveTo(l,b,l,m);e.quadraticCurveTo(l,d,c,d)}
function eb(a,c){var d=a.a;if(d.Rd){c.save();var b=a.f*a.zc,e=a.f,f=c.createLinearGradient(-.5*b,0,.5*b,0);f.addColorStop(0,c.strokeStyle);f.addColorStop(.5,"black");f.addColorStop(1,c.strokeStyle);var h=c.createLinearGradient(0,0,0,.5*e);h.addColorStop(0,"#999");h.addColorStop(.5,"#999");h.addColorStop(1,c.strokeStyle);c.createLinearGradient(0,.5*e,0,0);h.addColorStop(0,"#999");h.addColorStop(.5,"#999");h.addColorStop(1,c.strokeStyle);h=c.createLinearGradient(-.5*b,0,.5*b,0);h.addColorStop(0,"#999");
h.addColorStop(.3,"#999");h.addColorStop(.4,c.strokeStyle);h.addColorStop(.6,c.strokeStyle);h.addColorStop(.7,"#999");h.addColorStop(1,"#999");var g=new C(d.c);if(a.W)for(var l=a.W.length,m=0;m<l;++m){var n=a.W[m];g.set(0);for(var u=0;u<n.length;++u)g.v(n[u].h),g.v(n[u].o),g.v(n[u].Ha);for(n=0;n<d.c;++n)g.O(n)||(c.beginPath(),c.moveTo(b*(m-.51),e*n),c.lineTo(b*(m+.51),e*n),c.stroke())}else for(var l=a.s.length,m=0;m<l;++m)for(g.set(0),g.v(a.s[m].h),g.v(a.s[m].o),g.v(a.s[m].Ha),n=0;n<d.c;++n)g.O(n)||
(c.beginPath(),c.moveTo(b*(m-.51),e*n),c.lineTo(b*(m+.51),e*n),c.stroke());for(d=0;d<a.s.length;++d){c.save();var k=a.s[d];null!=k.Da?c.translate(b*k.Da,0):c.translate(b*d,0);var g=k.h.V(),m=k.h.P(),l=k.o.V(),u=k.o.P(),v=Math.max(g,l),n=Math.min(m,u),r=!1;if("write"==k.b){r=!0;for(c.beginPath();n<=v;n+=2)if(k.h.O(n)){var p=-.1*b,t=(n-1)*e,w=.5*b,x=(n+0)*e,z=.4*e,B=.1*e,J=p+.1*(w-p),P=p+.4*(w-p),Z=p+.6*(w-p),aa=p+.9*(w-p),ga=.5*(p+w),Pa=.5*(t+x);Y(J,P,t,t+z,c);Y(J,P,x,x-z,c);Y(Z,aa,t,t+z,c);Y(Z,aa,
x,x-z,c);c.moveTo(p,t);c.lineTo(J,t);c.moveTo(P,t);c.lineTo(Z,t);c.moveTo(aa,t);c.lineTo(w,t);c.moveTo(p,x);c.lineTo(J,x);c.moveTo(P,x);c.lineTo(Z,x);c.moveTo(aa,x);c.lineTo(w,x);c.moveTo(p,ba);c.lineTo(M,ba);c.moveTo(N,ba);c.lineTo(w,ba);z=p+.3*(w-p);p+=.6*(w-p);w=.5*(z+p);J=B;B*=3;P=.5*(J+B);c.moveTo(w,t-J);c.quadraticCurveTo(z,t-P,w,t-B);c.quadraticCurveTo(p,t-P,w,t-J);c.moveTo(w,x+J);c.quadraticCurveTo(z,x+P,w,x+B);c.quadraticCurveTo(p,x+P,w,x+J)}c.stroke()}else if(("dual_rail_beamsplitter"==
k.b||"exchange"==k.b||"cexchange"==k.b||"rootexchange"==k.b||"rootexchange_inv"==k.b)&&g==m+1)if("exchange"==k.b&&0>u)r=!0,p=-.5*b,t=m*e,w=.5*b,x=g*e,ga=.5*(p+w),Pa=.5*(t+x),c.save(),c.strokeStyle=f,c.beginPath(),c.moveTo(p,t),c.quadraticCurveTo(.5*(p+ga),t,ga,Pa),c.quadraticCurveTo(.5*(w+ga),x,w,x),c.stroke(),c.restore(),c.beginPath(),c.moveTo(p,x),c.quadraticCurveTo(.5*(p+ga),x,ga,Pa),c.quadraticCurveTo(.5*(w+ga),t,w,t),c.stroke();else if("dual_rail_beamsplitter"==k.b){var r=!0,p=-.5*b,t=m*e,w=
.5*b,x=g*e,ba=u*e,z=.4*e,M=p+.3*(w-p),N=p+.7*(w-p);c.beginPath();Y(p,w,t,t+z,c);c.moveTo(p,x);Y(p,w,x,x-z,c);c.stroke()}else u!=l||u!=m-1&&u!=g+1||(r=!0,p=-.5*b,t=m*e,w=.5*b,x=g*e,ba=u*e,z=.4*e,B=.1*e,J=p+.1*(w-p),P=p+.3*(w-p),M=p+.3*(w-p),N=p+.7*(w-p),Z=p+.7*(w-p),aa=p+.9*(w-p),c.beginPath(),Y(J,P,t,t+z,c),Y(J,P,x,x-z,c),Y(M,N,t,t-z,c),u<m&&Y(M,N,t-e,t-e+z,c),Y(M,N,x,x+z,c),u>m&&Y(M,N,x+e,x+e-z,c),Y(Z,aa,t,t+z,c),Y(Z,aa,x,x-z,c),c.moveTo(p,t),c.lineTo(J,t),c.moveTo(P,t),c.lineTo(M,t),c.moveTo(N,
t),c.lineTo(Z,t),c.moveTo(aa,t),c.lineTo(w,t),c.moveTo(p,x),c.lineTo(J,x),c.moveTo(P,x),c.lineTo(M,x),c.moveTo(N,x),c.lineTo(Z,x),c.moveTo(aa,x),c.lineTo(w,x),c.moveTo(p,ba),c.lineTo(M,ba),c.moveTo(N,ba),c.lineTo(w,ba),c.stroke(),c.save(),u>m?(c.strokeStyle=h,c.beginPath(),Y(M,N,t-z-2*B-z/8,t-z-2*B,c)):(c.strokeStyle=h,c.beginPath(),Y(M,N,x+z+2*B+z/8,x+z+2*B,c)),c.stroke(),c.restore(),k.Ha&&(n=k.Ha.P(),0<=n&&(k=n*e,n>m?(c.beginPath(),Y(M,N,k,k+z,c),c.stroke(),c.save(),c.strokeStyle=h,c.beginPath(),
Y(M,N,k+z+2*B+z/8,k+z+2*B,c)):(c.beginPath(),Y(M,N,k,k-z,c),c.stroke(),c.save(),c.strokeStyle=h,c.beginPath(),Y(M,N,k-z-2*B-z/8,k-z-2*B,c)),c.stroke(),c.restore(),c.beginPath(),c.moveTo(p,k),c.lineTo(M,k),c.moveTo(N,k),c.lineTo(w,k),c.stroke())));r||(c.save(),c.fillStyle="red",c.strokeStyle="red",c.globalAlpha=.5,c.lineWidth=8,0<=l&&(Q(c,0,e*l,.5*e),Q(c,0,e*u,.5*e)),0<=g&&(R(c,0,e*g,.5*e),R(c,0,e*m,.5*e)),c.restore());c.restore()}c.restore()}};(new function(){this.dd=!0;this.uf=function(){this.print("Runnnig all tests...");this.dd=!0;this.ld(1,1);this.ld(8,8);this.ld(8,4);this.jd(1,1);this.jd(8,8);this.jd(8,4);this.kd(1,1);this.kd(8,8);this.kd(8,4);this.hd(1,1);this.hd(8,8);this.hd(8,4);this.md(1,1);this.md(8,8);this.md(8,4);this.dd?this.print("...passed."):this.print("...FAILED.")};this.print=function(){};this.error=function(){this.dd=!1};this.ld=function(a,c){this.print("Testing Not... "+a+"/"+c);var d=new K(a,c,!1);d.pb();var b=0&d.J;
ya(d,b);O(d)!=b&&this.error("  : write and read don't match: ("+O(d)+" != "+b+")");for(var e=0;e<a;++e){var f=1<<e;d.X(f);b^=f;O(d)!=b&&this.error("  error in bit "+e+" ("+O(d)+" != "+b+")")}};this.jd=function(a,c){this.print("Testing CNot... "+a+"/"+c);var d=new K(a,c,!1);d.pb();var b=21845&d.J;ya(d,b);O(d)!=b&&this.error("  : write and read don't match: ("+O(d)+" != "+b+")");for(var e=0;e<a;++e)for(var f=0;f<1<<a-1;++f){var h=1<<e,g=f>>e<<e+1|f&h-1,g=g&d.J,l=b,m=O(d);d.G(h,g);(b&g)==g&&(b^=h);var n=
O(d);d.Tc();var u=O(d);u==n&&n==b||this.error("  error in bit "+e+" of "+a+"/"+c+" prevTracker:"+l+" prevReg:"+m+" target:"+h+" cond:"+g+" ( quantum:"+u+" class:"+n+" trk:"+b+")")}};this.kd=function(a,c){this.print("Testing Hadamard... "+a+"/"+c);var d=new K(a,c,!1);d.pb();var b=0&d.J;ya(d,b);O(d)!=b&&this.error("  : write and read don't match: ("+O(d)+" != "+b+")");d.Ca(1)};this.hd=function(a,c){this.print("Testing CHadamard... "+a+"/"+c);var d=new K(a,c,!1);d.pb();var b=21845&d.J;ya(d,b);O(d)!=
b&&this.error("  : write and read don't match: ("+O(d)+" != "+b+")");d.gc(1,2)};this.md=function(a,c){this.print("Testing Phase Shift... "+a+"/"+c);var d=new K(a,c,!1);d.pb();var b=0&d.J;ya(d,b);O(d)!=b&&this.error("  : write and read don't match: ("+O(d)+" != "+b+")");d.sa(1)}}).uf();function na(){this.ua=this.active=!1;this.reset=function(a){this.a=a;La&&(La.I=this,null==a&&(a=La.a));if(a){a.I=this;var c={};this.Sa=c;this.Xe(c,a.c);this.ua&&(this.zb(c),this.Ab(c))}};this.G=function(a,c,d){null==a&&(a=this.Sa);var b,e,f;b=c>>5;e=d>>5;c=a.M[c&31];f=a.M[d&31];for(d=0;d<2*a.n;d++)a.x[d][b]&c&&(a.x[d][e]^=f),a.z[d][e]&f&&(a.z[d][b]^=c),a.x[d][b]&c&&a.z[d][e]&f&&a.x[d][e]&f&&a.z[d][b]&c&&(a.r[d]=(a.r[d]+2)%4),!(a.x[d][b]&c&&a.z[d][e]&f)||a.x[d][e]&f||a.z[d][b]&c||(a.r[d]=(a.r[d]+2)%
4);this.ua&&(this.zb(a,"after CNOT:"),this.Ab(a))};this.Ca=function(a,c){null==a&&(a=this.Sa);var d,b,e,f;e=c>>5;f=a.M[c&31];for(d=0;d<2*a.n;d++)b=a.x[d][e],a.x[d][e]^=(a.x[d][e]^a.z[d][e])&f,a.z[d][e]^=(a.z[d][e]^b)&f,a.x[d][e]&f&&a.z[d][e]&f&&(a.r[d]=(a.r[d]+2)%4);this.ua&&(this.zb(a,"after HAD:"),this.Ab(a))};this.yc=function(a,c){null==a&&(a=this.Sa);var d,b,e;b=c>>5;e=a.M[c&31];for(d=0;d<2*a.n;d++)a.x[d][b]&e&&a.z[d][b]&e&&(a.r[d]=(a.r[d]+2)%4),a.z[d][b]^=a.x[d][b]&e;this.ua&&(this.zb(a,"after PHASE:"),
this.Ab(a))};this.Zb=function(a,c,d){var b;for(b=0;b<a.ab;b++)a.x[c][b]=a.x[d][b],a.z[c][b]=a.z[d][b];a.r[c]=a.r[d]};this.Ec=function(a,c,d){this.Zb(a,2*a.n,d);this.Zb(a,d,c);this.Zb(a,c,2*a.n)};this.tf=function(a,c,d){var b;for(b=0;b<a.ab;b++)a.x[c][b]=0,a.z[c][b]=0;a.r[c]=0;d<a.n?a.x[c][d>>5]=a.M[d&31]:(b=d-a.n>>5,d=d-a.n&31,a.z[c][b]=a.M[d])};this.re=function(a,c,d){var b,e,f,h=0;for(b=0;b<a.ab;b++)for(e=0;32>e;e++)f=a.M[e],a.x[d][b]&f&&!(a.z[d][b]&f)&&(a.x[c][b]&f&&a.z[c][b]&f&&h++,!(a.x[c][b]&
f)&&a.z[c][b]&f&&h--),a.x[d][b]&f&&a.z[d][b]&f&&(!(a.x[c][b]&f)&&a.z[c][b]&f&&h++,a.x[c][b]&f&&!(a.z[c][b]&f)&&h--),!(a.x[d][b]&f)&&a.z[d][b]&f&&(a.x[c][b]&f&&!(a.z[c][b]&f)&&h++,a.x[c][b]&f&&a.z[c][b]&f&&h--);h=(h+a.r[c]+a.r[d])%4;return 0<=h?h:h+4};this.cb=function(a,c,d){var b;a.r[c]=this.re(a,c,d);for(b=0;b<a.ab;b++)a.x[c][b]^=a.x[d][b],a.z[c][b]^=a.z[d][b]};this.Ab=function(a){null==a&&(a=this.Sa);var c,d,b,e;for(c=0;c<2*a.n;c++){if(c==a.n)for(this.print("\n"),d=0;d<a.n+1;d++)this.print("-");
2==a.r[c]?this.print("\n-"):this.print("\n+");for(d=0;d<a.n;d++)b=d>>5,e=a.M[d&31],a.x[c][b]&e||a.z[c][b]&e||this.print("I"),a.x[c][b]&e&&!(a.z[c][b]&e)&&this.print("X"),a.x[c][b]&e&&a.z[c][b]&e&&this.print("Y"),!(a.x[c][b]&e)&&a.z[c][b]&e&&this.print("Z")}this.print("\n")};this.measure=function(a,c,d){null==a&&(a=this.Sa);var b=0,e,f,h;f=c>>5;h=a.M[c&31];for(e=0;e<a.n&&(a.x[e+a.n][f]&h&&(b=1),!b);e++);if(b){d=0|Math.floor(2*Math.random());this.Zb(a,e,e+a.n);this.tf(a,e+a.n,c+a.n);a.r[e+a.n]=d<<1;
for(c=0;c<2*a.n;c++)c!=e&&a.x[c][f]&h&&this.cb(a,c,e);return a.r[e+a.n]?3:2}if(!b&&!d){for(e=0;e<a.n&&!(a.x[e][f]&h);e++);this.Zb(a,2*a.n,e+a.n);for(c=e+1;c<a.n;c++)a.x[c][f]&h&&this.cb(a,2*a.n,c+a.n);if(a.r[2*a.n])return 1}return 0};this.Ed=function(a){null==a&&(a=this.Sa);var c=a.n,d,b,e,f,h;for(b=0;b<a.n;b++){e=b>>5;h=a.M[b&31];for(d=c;d<2*a.n&&!(a.x[d][e]&h);d++);if(d<2*a.n){this.Ec(a,c,d);this.Ec(a,c-a.n,d-a.n);for(d=c+1;d<2*a.n;d++)a.x[d][e]&h&&(this.cb(a,d,c),this.cb(a,c-a.n,d-a.n));c++}}f=
c-a.n;for(b=0;b<a.n;b++){e=b>>5;h=a.M[b&31];for(d=c;d<2*a.n&&!(a.z[d][e]&h);d++);if(d<2*a.n){this.Ec(a,c,d);this.Ec(a,c-a.n,d-a.n);for(d=c+1;d<2*a.n;d++)a.z[d][e]&h&&(this.cb(a,d,c),this.cb(a,c-a.n,d-a.n));c++}}return f};this.Sd=function(a){null==a&&(a=this.Sa);var c,d,b,e=a.r[2*a.n];for(c=0;c<a.n;c++)d=c>>5,b=a.M[c&31],a.x[2*a.n][d]&b&&a.z[2*a.n][d]&b&&(e=(e+1)%4);0==e&&this.print("\n +|");1==e&&this.print("\n+i|");2==e&&this.print("\n -|");3==e&&this.print("\n-i|");for(c=0;c<a.n;c++)d=c>>5,b=a.M[c&
31],a.x[2*a.n][d]&b?this.print("1"):this.print("0");this.print(">")};this.Vd=function(a,c){var d,b,e,f,h,g;for(b=a.r[2*a.n]=0;b<a.ab;b++)a.x[2*a.n][b]=0,a.z[2*a.n][b]=0;for(d=2*a.n-1;d>=a.n+c;d--){h=a.r[d];for(b=a.n-1;0<=b;b--)e=b>>5,f=a.M[b&31],a.z[d][e]&f&&(g=b,a.x[2*a.n][e]&f&&(h=(h+2)%4));2==h&&(e=g>>5,f=a.M[g&31],a.x[2*a.n][e]^=f)}};this.zb=function(a,c){null==a&&(a=this.Sa);var d,b,e,f;c&&this.print(c);d=this.Ed(a);this.print("\n2^"+d+" nonzero basis states");if(31<d)this.print("\nState is WAY too big to print");
else{this.Vd(a,d);this.Sd(a);for(b=0;b<a.M[d]-1;b++){e=b^b+1;for(f=0;f<d;f++)e&a.M[f]&&this.cb(a,2*a.n,a.n+f);this.Sd(a)}this.print("\n")}};this.print=function(a){La.print(a)};this.Vc=function(a){return new Uint32Array(new ArrayBuffer(4*a))};this.$e=function(a){return new Int32Array(new ArrayBuffer(4*a))};this.Xe=function(a,c){var d,b;a.n=c;a.x=Array(2*a.n+1);a.z=Array(2*a.n+1);a.r=this.$e(2*a.n+1);a.ab=(a.n>>5)+1;a.M=this.Vc(32);for(d=a.M[0]=1;32>d;d++)a.M[d]=2*a.M[d-1];for(d=0;d<2*a.n+1;d++){a.x[d]=
this.Vc(a.ab);a.z[d]=this.Vc(a.ab);for(b=0;b<a.ab;b++)a.x[d][b]=0,a.z[d][b]=0;d<a.n?a.x[d][d>>5]=a.M[d&31]:d<2*a.n&&(b=d-a.n,a.z[d][b>>5]=a.M[b&31]);a.r[d]=0}this.ua&&(this.zb(a,"after init:"),this.Ab(a));this.ua&&(this.zb(a,"after prepare:"),this.Ab(a))};this.Kf=function(){this.reset(this.a)};this.ae=function(){var a=q,c,d,b,e=a.r[2*a.n];for(c=0;c<a.n;c++)d=c>>5,b=a.M[c&31],a.x[2*a.n][d]&b&&a.z[2*a.n][d]&b&&(e=(e+1)%4);var f=0,h=0;0==e?f=1:1==e?h=1:2==e?f=-1:3==e&&(h=-1);for(c=e=0;c<a.n;c++)d=c>>
5,b=a.M[c&31],a.x[2*a.n][d]&b&&(e|=1<<c);this.a.Ea(e,f,h)};this.be=function(){this.a.Fa();q=this.Sa;var a,c,d,b;a=this.Ed(q);if(31<a)this.print("\nState is WAY too big to transfer.");else{this.Vd(q,a);this.ae();for(c=0;c<q.M[a]-1;c++){d=c^c+1;for(b=0;b<a;b++)d&q.M[b]&&this.cb(q,2*q.n,q.n+b);this.ae()}xa(this.a);this.a.K()}}};